### PR TITLE
Replace inactive owners

### PR DESCRIPTION
**Pull request by nckturner**
Replace inactive owners in provider-aws

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Review by nikhita — APPROVED** [review]
@nckturner can you also update the OWNERS in https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES#L170?

Approving based on @andrewsykim's approval (SIG Cloud Provider lead)

/approve

**Pull request merged**
