### PR TITLE
Add sdmodi to cloud-provider-gcp-maintainers

### PR DESCRIPTION
**Pull request by sdmodi**
Adding myself to cloud-provider-gcp-maintainers as I am going to be working on that code.

### CODE REVIEW

**Comment by cici37** [comment]
You may also want to add yourself as a Kubernetes member in the same file :)

**Comment by savitharaghunathan** [comment]
/hold 

Kubernetes membership is done through sponsorship and needs atleast two kubernetes approvers/reviewers from a different company endorsing the membership. cc: @mrbobbytables @nikhita checking in to see if that doesn't apply here. 

Please cancel hold once we have a clarification.

**Comment by mrbobbytables** [comment]
It does apply.
@sdmodi please open an [Org Membership Request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E). 

You can PR yourself into other orgs once approved to join the Kubernetes project, but till then it must go through the review process.

**Comment by dims** [comment]
@sdmodi please watch the #cluster-api-gcp channel as well.

**Pull request closed without merging**
