### PR TITLE
Add eddiezane to kubectl-admins and prune

### PR DESCRIPTION
**Pull request by eddiezane**
This PR adds myself as an admin to the [kubectl GitHub repo](https://github.com/kubernetes/kubectl). Requesting this as sig cli co-chair to make issue cleanup easier.

### CODE REVIEW

**Comment by nikhita** [comment]
@eddiezane I noticed that there are some people on this team who are not active in the project anymore. Would it make sense to prune here?

The team grants admin access to the kubectl repo, which has published code from staging so I want to ensure that we don't have cases of any accidental merges.

**Comment by eddiezane** [comment]
@nikhita good call. I added commit 11d6c2aa981c08d345da6853a1b3a73c0abb7ece to clean that up a bit.

**Comment by nikhita** [comment]
/approve

Will lgtm to @soltysh :)

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
