### PR TITLE
cleanup docs teams

### PR DESCRIPTION
**Pull request by jimangel**
ref: https://github.com/kubernetes/website/issues/24170

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @jimangel! This looks good to me, but also looks like it needs a rebase.

**Comment by savitharaghunathan** [comment]
Hi, @jimangel 👋 , friendly reminder: This PR still needs a rebase. Can you fix the conflicts when you get some time :) Thanks!

**Comment by jimangel** [comment]
@onlydole @savitharaghunathan thanks for the friendly pings, sorry to "homer into the bushes" on this one.

Should be good to go! Thanks!

image

**Review by onlydole — APPROVED** [review]
Thank you, @jimangel!

/lgtm

**Pull request merged**
