### PR TITLE
Add priyankasaggu11929 as GitHub Admin

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
Ref https://github.com/kubernetes/community/pull/7464

**Commit 1**

`.*: add Priyankasaggu11929 and rotate out idvoretskyi as admin`

Change root OWNERS and ADMIN variables in scripts.

**Commit 2**

`remove Priyankasaggu11929 from wg-structured-logging teams.yaml`

**Commit 3**

`config: GH admin rotation - update team configs`

Move idvoretskyi to members wherever applicable.
Add Priyankasaggu11929 as maintainer anew or move from member to maintainer wherever necessary.

**Commit 4**

`config: GH Admin rotation - upgrade org OWNERS and configs`
    
Add Priyankasaggu11929 as admin in all orgs and move idvoretskyi to member wherever applicable.
Add Priyankasaggu11929 as reviewer and approver in OWNERS of all orgs and move idvoretskyi to emiratus.

/cc https://github.com/orgs/kubernetes/teams/owners
/assign @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
Lgtm after rebase

**Comment by Priyankasaggu11929** [comment]
@nikhita, rebased the PR. PTAL. Thanks! :slightly_smiling_face:

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

Congratulations!

**Pull request merged**
