### PR TITLE
Adding andrewpollack to wg structured logging

### PR DESCRIPTION
**Pull request by andrewpollack**
Adding andrewpollack to wg structured logging

### CODE REVIEW

**Comment by serathius** [comment]
Not sure if you need to be kubernetes org member. Let's try 
/ok-to-test

**Comment by andrewpollack** [comment]
> Not sure if you need to be kubernetes org member. Let's try

Looks like it won't work as the test build failed with reasoning:
```

--- FAIL: TestAllOrgs (0.04s)
    config_test.go:251: The following members of team wg-structured-logging-reviews are not Kubernetes org members: andrewpollack
    config_test.go:251: The following members of team wg-structured-logging-members are not Kubernetes org members: andrewpollack
```

Is there a way I can be notified for the issues in a different way? 🙏

**Comment by serathius** [comment]
Hey @andrewpollack , feel free to reach out on #wg-structured-logging slack channel. Will try to help with joining the org.

**Comment by spiffxp** [comment]
/close
Trying to keep our open PR count down, please feel free to /reopen once you've joined as an org member and rebased this PR (or open a new one)

**Pull request closed without merging**
