### PR TITLE
Update teams.yaml

### PR DESCRIPTION
**Pull request by mickeyboxell**
Adding Mickey Boxell (me) as 1.27 Docs lead.

### CODE REVIEW

**Comment by mickeyboxell** [comment]
@reylejano

**Comment by reylejano** [comment]
This PR also removes the 1.26 Docs lead as it is the end of the 1.27 release cycle
/approve
/assign @natalisucks @divya-mohan0209

**Review by onlydole — APPROVED** [review]
/lgtm 

Thank you, @mickeyboxell, and @reylejano

**Review by nate-double-u — COMMENTED** [review]
/lgtm

**Pull request merged**
