### PR TITLE
add Dan Winship as an admin

### PR DESCRIPTION
**Pull request by astoycos**
Fixes https://github.com/kubernetes-sigs/network-policy-api/issues/118

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
/approve
/lgtm

**Comment by palnabarun** [comment]
No problem! I had retested because of the pod timeouts with the presubmits.

**Review by palnabarun — APPROVED** [review]
/lgtm

(relgtming the existing reviewers ack since there was a change)

**Pull request merged**
