### PR TITLE
Update teams.yaml

### PR DESCRIPTION
**Pull request by mickeyboxell**
Adding myself to sig-docs-en-owners as the Docs Lead for 1.27 and removing the previous lead. Adding the 1.27 docs release team to the website-milestone-maintainers group.

### CODE REVIEW

**Comment by mickeyboxell** [comment]
@reylejano 
/sig docs

**Comment by reylejano** [comment]
/approve
@mickeyboxell was added as a sig-docs-en-owners in PR https://github.com/kubernetes/website/pull/40273

**Pull request merged**
