### PR TITLE
Add new members (181030)

### PR DESCRIPTION
**Pull request by justaugustus**
Fixes: #202 
Fixes: #203 
Fixes: #204 
Fixes: #205 
Fixes: #206 
Fixes: #209 
Fixes: #210 
Fixes: #211 

/assign @cblecker

### CODE REVIEW

**Comment by ant31** [comment]
@justaugustus thank you !

**Comment by mrbobbytables** [comment]
Thanks @justaugustus for tackling all the open requests! :) 

/lgtm

**Comment by woopstar** [comment]
@justaugustus thanks!

**Comment by spiffxp** [comment]
/hold 
ref: https://github.com/kubernetes/org/issues/174#issuecomment-431137034
>Right now our policies are set up that membership in @kubernetes automatically qualifies you for membership in other k8s orgs as required.. this doesn't necessarily apply in the other direction however (membership in @kubernetes-incubator doesn't automatically get you @kubernetes-sigs membership)

#203 needs sponsors
#204 needs sponsors
#205 needs sponsors
#206 needs one more sponsor +1
#209 needs sponsors to +1

**Comment by spiffxp** [comment]
If this has changed let me know, but last time I asked about relaxing for exactly this purpose (thanks for choosing to migrate to kubernetes-sigs kubespray folk!) I got back a negative response.  There was a long period of time where membership in kubernetes-incubator was _completely_ arbitrary, so we can't make any guarantees of already having been vetted like we can for kubernetes, even if the repo being migrated is actively under development.

I'm happy to act as a sponsor if anyone needs one.

**Comment by ant31** [comment]
@spiffxp all of them have been added recently to the incubator. 
If possible, I'll be one of the sponsors.

For reference:   
#203 -> added in #50 (Sept 5th 2018)
#204 -> added in #19 (August 22th 2018)
#206 -> added in #21 (August 22th 2018)
#209 -> added in #31 (August 23th 2018)
#205 (added a long time ago)

**Comment by justaugustus** [comment]
@spiffxp @ant31 -- I've added my sponsorship to each of these.

I've also opened an issue to discuss the sponsorship not being inversely applicable: https://github.com/kubernetes/community/issues/2883

I believe we can unhold and should just need a `/approve` now.
/hold cancel

**Comment by spiffxp** [comment]
/hold cancel
/approve
@ant31 thank you for doing the legwork, PR churn has destroyed my memory

**Comment by spiffxp** [comment]
@justaugustus thanks for the issue, we should have opened one last time

**Pull request merged**
