### PR TITLE
Add members 2024-05-17

### PR DESCRIPTION
**Pull request by ydFu**
This PR:

- Fixed https://github.com/kubernetes/org/issues/4953

/area github-membership

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by ydFu** [comment]
> ```
> config_test.go:263: members for Kubernetes org are unsorted
> ```
> 
> The list needs to be sorted

Thanks for the reminder, the adjustment has been completed.

**Pull request merged**
