### PR TITLE
Update 1.22 CI Signal shadows for release-team, ci-signal

### PR DESCRIPTION
**Pull request by mkorbi**
- Adds 1.22 CI Signal shadows to the release-team, ci-signal teams
- Removes 1.21 CI Signal shadows from those teams

Welcome to the team, y'all! 🎉

### CODE REVIEW

**Comment by mkorbi** [comment]
going to reach out to encodeflush, lambdanis for their kube membership

**Comment by palnabarun** [comment]
/lgtm

leaving approval for @kubernetes/sig-release-leads

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
