### PR TITLE
Add sbueringer & fabriziopandini to cluster-api-admins

### PR DESCRIPTION
**Pull request by sbueringer**
Adding myself and Fabrizio to Cluster API admins.

The idea is that through the admin access to the repo we will also get access to Netlify.

Adding Fabrizio as well so he can also help out with Netlify duties.

xref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1669656532332839?thread_ts=1669638214.266839&cid=C1TU9EB9S

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
/assign @fabriziopandini 
/assign @vincepri 
for approval

**Comment by fabriziopandini** [comment]
+1 for me

**Comment by sbueringer** [comment]
Not sure what the next steps are one of `sig-cluster-lifecycle-leads` has to approve

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
