### PR TITLE
Add hzxuzhonghu to kubernetes-sigs

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fixes : #707

### CODE REVIEW

**Comment by cblecker** [comment]
@hzxuzhonghu normally adding folks to the org is left to our membership coordinators, but as you're already in the @kubernetes org, you're automatically eligible for @kubernetes-sigs membership.

**Comment by hzxuzhonghu** [comment]
Thanks for your clarification.

**Comment by nikhita** [comment]
@hzxuzhonghu Can you edit the commit message to `Add hzxuzhonghu to kubernetes-sigs` instead of `Add members 2019-04-11`? There are some more membership requests and IMO it would be appropriate to bundle those into another PR which says `Add members 2019-04-11`.

**Comment by hzxuzhonghu** [comment]
@nikhita Done

**Pull request merged**
