### PR TITLE
Add detiber to cluster-api-provider-packet-{admins|maintainers}

### PR DESCRIPTION
**Pull request by detiber**
Adding myself as an additional admin/maintainer for cluster-api-provider-packet

/assign @deitch @thebsdbox

### CODE REVIEW

**Comment by timothysc** [comment]
/approve 
to unblock

**Comment by detiber** [comment]
Doh, of course the bot wanted the list sorted...  Fixed.

**Comment by deitch** [comment]
(is there a bot command that says, "approve anything from @detiber"? :-) )

**Comment by detiber** [comment]
@deitch believe this just needs an `/lgtm` at this point

**Comment by deitch** [comment]
(lrtm = looks really-good to me)

**Pull request merged**
