### PR TITLE
Update contributor comms team

### PR DESCRIPTION
**Pull request by AvineshTripathi**
Update Contributor comms team

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Please update the commit message to be more descriptive of the change. There are dozens of teams.yaml files in this repo

/hold

**Comment by AvineshTripathi** [comment]
@mrbobbytables do I need to do commit for every add or remove of member?

**Comment by mrbobbytables** [comment]
Nah, we only require that for adding/removing people from orgs, but something like "Updating contributor comms team" would cover it, essentially if looking at the git log can you get an idea of what was done.

**Comment by mrbobbytables** [comment]
@chris-short the test failure has been the same, as the previous run, thr list is not an alpha sorted list.

**Comment by mrbobbytables** [comment]
You'll want to squash the commits and change the commit message for the commit.

**Comment by mrbobbytables** [comment]
Thanks!
/hold cancel
/approve

**Pull request merged**
