### PR TITLE
Add dashpole and logicalhan to milestone maintainers

### PR DESCRIPTION
**Pull request by dashpole**
Based on https://github.com/kubernetes/enhancements/pull/1554, as a sig lead for instrumentation I should be able to triage PRs.

cc @brancz @logicalhan

### CODE REVIEW

**Comment by logicalhan** [comment]
Would you mind adding me in there too?

**Comment by dashpole** [comment]
@logicalhan done

**Comment by logicalhan** [comment]
Thanks! 

/lgtm

**Pull request merged**
