### PR TITLE
Remove inactive members

### PR DESCRIPTION
**Pull request by nckturner**
Remove inactive members and add new members.
    
Inactive is defined as:
- no recent contributions to the AWS cloud provider
- not attending sig-cloud-provider meetings
- not attenting provider-aws meetings
    
Adding team members from AWS and/or sig-cloud-provider:
- @wongma7
- @nckturner
- @andrewsykim

/cc @andrewsykim @cheftako

### CODE REVIEW

**Comment by nikhita** [comment]
> config_test.go:251: The team provider-aws-misc in org Kubernetes has an unsorted list of members

@nckturner the members need to be listed in the alphabetical order :)

**Comment by cheftako** [comment]
/lgtm
I wonder if we might want cloud provider leads on the AWS list?
Also I think individual cloud provider milestone maintainers should probably not be needed once cloud provider extraction is completed.

**Comment by nckturner** [comment]
@cheftako I added andrew to  provider-aws-misc, I'm guessing you meant  to release team?  Happy to include both of you there in this PR if that's what you're referring to.

**Comment by nckturner** [comment]
Also related PR: https://github.com/kubernetes/test-infra/pull/19138

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
