### PR TITLE
Add new memberships - October 18th

### LINKED ISSUE #170: REQUEST: New membership for m1kola
### GitHub Username
@m1kola

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @soltysh 
- @seans3 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/67573
  - https://github.com/kubernetes/kubernetes/pull/69500
  - https://github.com/kubernetes/kubernetes/pull/69477
  - https://github.com/kubernetes/kubernetes/pull/67860
  - https://github.com/kubernetes/kubernetes/pull/67316
  - https://github.com/kubernetes/kubernetes/pull/66692
  - https://github.com/kubernetes/kubernetes/pull/66463
- Issues responded to
  - https://github.com/kubernetes/kubectl/issues/542
  - https://github.com/kubernetes/kubectl/issues/535
- SIG projects I am involved with
  - sig-cli

/area github-membership

### LINKED ISSUE #173: REQUEST: New membership for code-sleuth
### GitHub Username
@code-sleuth

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @juanvallejo 
- @seans3 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
	- https://github.com/kubernetes/kubernetes/pull/69897
	- https://github.com/kubernetes/kubernetes/pull/69581
- Issues responded to
	- https://github.com/kubernetes/kubernetes/issues/69555
- SIG projects I am involved with
	- sig-cli

/area github-membership

### LINKED ISSUE #175: REQUEST: New membership for danehans
### GitHub Username
@danehans

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pmorie  
- @marun 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Adanehans

/area github-membership

### PR DESCRIPTION
**Pull request by cblecker**
fixes #170
fixes #173
fixes #175

### CODE REVIEW

**Comment by danehans** [comment]
@cblecker and @mrbobbytables I am working on the [federation-v2](https://github.com/kubernetes-sigs/federation-v2) project and maintainers are still unable to assign reviews to me. See https://github.com/kubernetes-sigs/federation-v2/pull/353#issuecomment-432273485 Are any additional steps needed?

/cc @pmorie

**Comment by cblecker** [comment]
@danehans You need to actually accept the invite. It will be in your e-mail, or at https://github.com/kubernetes-sigs

**Comment by danehans** [comment]
The link worked. Thanks for your help. I'm good to go.

**Pull request merged**
