### PR TITLE
Refresh of Cluster API Provider vSphere team members

### PR DESCRIPTION
**Pull request by randomvariable**
Update of CAPV team members as was discussed in 2023/06/22 meeting.

Related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2082/files

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/hold
In case Naadir wants to wait with merge

cc @srm09 @yastij

/assign @vincepri
(fabrizio is on PTO)

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
