### PR TITLE
add claurence to milestone-maintainers

### PR DESCRIPTION
**Pull request by claurence**
As 1.14 enhancements lead I think I should be able to add milestones to issues in the enhancements repo 

@spiffxp @justaugustus lmk if this isn't something I should have access to do

### CODE REVIEW

**Comment by cblecker** [comment]
@claurence you'll need to sign the CLA. Instructions are [above](https://github.com/kubernetes/org/pull/377#issuecomment-455278391).

**Comment by cblecker** [comment]
it doesn't seem to be registered in the system under your pivitol.io address. You shouldn't need to sign an individual if you have a corporate one. You may need to check again with your internal team and/or open a ticket with the CNCF/LF helpdesk (e-mail to do that is in the above comment from the bot)

**Comment by claurence** [comment]
bumping the comment to re-run the check on the CLA

**Comment by claurence** [comment]
@cblecker the CLA issue was resolved - not sure what is causing the other failures - let me know what else I can do to fix those

**Pull request merged**
