### PR TITLE
Add irvifa as sig-docs-pr-reviews as preparation for shadowing role

### PR DESCRIPTION
**Pull request by irvifa**
As previous discussion in sig docs I need an access as sig-docs-pr-reviewers

### CODE REVIEW

**Comment by onlydole** [comment]
Howdy, @irvifa! 

/lgtm

**Comment by zacharysarah** [comment]
@irvifa Please add yourself to the English reviewer and approver blocks as well. L22, L46

**Comment by irvifa** [comment]
@zacharysarah I've added it, do I need to rebase it?

**Comment by zacharysarah** [comment]
@irvifa 

> do I need to rebase it?

Yes, in order to squash commits. 👍

**Comment by irvifa** [comment]
Closed in favor of https://github.com/kubernetes/org/pull/1972

**Pull request closed without merging**
