### PR TITLE
Add CecileRobertMichon as SIG Cluster Lifecycle Lead

### PR DESCRIPTION
**Pull request by vincepri**
@CecileRobertMichon

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Yay! congrats @CecileRobertMichon!
💯

**Comment by elmiko** [comment]
++ congrats!

**Comment by justinsb** [comment]
+1 from me - congrats & thank you @CecileRobertMichon

**Comment by justinsb** [comment]
/lgtm

(Trying on its own line)

**Comment by dlipovetsky** [comment]
+1 Congratulations @CecileRobertMichon :smile:

**Pull request merged**
