### PR TITLE
config: Rename cloud provider directories to provider-<cloud-provider>

### PR DESCRIPTION
**Pull request by andrewsykim**
SIG VMware doesn't exist anymore and should be renamed to "provider-vmware"

Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

### CODE REVIEW

**Comment by andrewsykim** [comment]
@justaugustus I didn't see this exist for any of the other providers in config/kubernetes-sigs, maybe I missed something :thinking:

**Comment by andrewsykim** [comment]
ah, I didn't check `config/kubernetes`. Yeah let me do that

**Comment by andrewsykim** [comment]
@justaugustus done!

**Comment by justaugustus** [comment]
/retitle config: Rename cloud provider directories to provider-<cloud-provider>

Thanks Andrew!
/lgtm
/approve

**Pull request merged**
