### PR TITLE
update sig-arch enhancements members

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Removing old RT Enhancements members and add 1.26 rt enhancements lead.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Pending PR creating group: https://github.com/kubernetes/k8s.io/pull/4176

**Comment by leonardpahlke** [comment]
@kikisdeliveryservice the referenced PR merged, we should be good to go with this one, right

**Comment by palnabarun** [comment]
I don't think this PR should be blocked on other PRs. The RT Enhancements members in the existing team are old members and can be removed.

**Comment by johnbelamaric** [comment]
/approve

sheesh

**Comment by kikisdeliveryservice** [comment]
the alias doesn't work here with the repo setup. added rt enhancemnets lead manually.

**Pull request merged**
