### PR TITLE
Add jichenjc into owner of cloud-provider-openstack

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/assign @cheftako @andrewsykim @nckturner 
For sign off of team + owners_aliases change

**Comment by jichenjc** [comment]
it has been 2 weeks for this PR , can anyone help on approve ? Thanks

**Comment by jichenjc** [comment]
@cheftako @andrewsykim @nckturner

can you help to approve this request? THanks

**Pull request merged**
