### PR TITLE
Add Kubernetes 1.27 Release Notes Team members to the GitHub organizations

### LINKED ISSUE #3935: REQUEST: New membership for sanchita-07
### GitHub Username

sanchita-07

### Organization you are requesting membership in

kubernetes
kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@harshanarayana 

### Sponsor 2

@JamesLaverack 

### List of contributions to the Kubernetes project

I am a shadow in SIG Release Notes of the Kubernetes v1.27 Release Team.

### LINKED ISSUE #3938: REQUEST: New membership for rjsadow
### GitHub Username

@rjsadow

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@harshanarayana

### Sponsor 2

@JamesLaverack

### List of contributions to the Kubernetes project

I am a shadow in SIG Release Notes of the Kubernetes v1.27 Release Team.

PRs:
[kubernetes/website](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Arjsadow+)
[kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3Arjsadow)

Issues:
[kubernetes/website](https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Arjsadow)
[kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues?q=is%3Aissue+author%3Arjsadow)

### LINKED ISSUE #3939: REQUEST: New membership for yrs147
### GitHub Username

yrs147

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@JamesLaverack

### Sponsor 2

@harshanarayana

### List of contributions to the Kubernetes project

I am a Release Notes shadow for the v1.27 release cycle.

### PR DESCRIPTION
**Pull request by harshanarayana**
Closes #3935
Closes #3938
Closes #3939

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold
We are VERY particular about the commit messages and changes for this repo as it is the canonical log of org memberships.

each member MUST be in their own commit following the format of:
Add <foo> to <org>

You can review the history in the repo for examples.

**Comment by harshanarayana** [comment]
@mrbobbytables I have updated the commit history. Sorry for the confusion earlier. PTAL when possible

**Comment by harshanarayana** [comment]
/hold 

Sponsorship requirements have not been met yet. Need one more +1 before we can merge this.

**Comment by palnabarun** [comment]
Add Kubernetes 1.27 Release Notes Team members to the GitHub organizations

**Comment by palnabarun** [comment]
/retitle 

Add Kubernetes 1.27 Release Notes Team members to the GitHub organizations

**Comment by nikhita** [comment]
This is done as a part of bulk membership additions - #3965. Closing.

**Comment by harshanarayana** [comment]
Thanks @nikhita

**Pull request closed without merging**
