### PR TITLE
Bump test-infra to 70b0b49

### PR DESCRIPTION
**Pull request by nikhita**
This PR bumps test-infra to https://github.com/kubernetes/test-infra/commit/70b0b49fe2476f06f97272e77f47ba432cb54244 to bring in the peribolos fix for syncing org meta (https://github.com/kubernetes/test-infra/pull/15579).

- The first commits updates go.mod (and go.sum) for bumping test-infra from `aef6d7642c3b` to `70b0b49fe247`.
- The second commit is the result of running `bazel run @io_k8s_repo_infra//hack:update-deps`. However, this leads to an error while running `bazel run //admin:update -- --github-token-path ~/path-to-my-token`

```
compilepkg: error running subcommand: exit status 2
/home/nikhita/.cache/bazel/_bazel_nikhita/706d61538fae541b06d3fd1b202fda16/sandbox/linux-sandbox/494/execroot/io_k8s_org/external/io_k8s_client_go/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
Target //admin:update failed to build
INFO: Elapsed time: 124.247s, Critical Path: 13.30s
INFO: 139 processes: 139 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
It looks like this is because `bazel run @io_k8s_repo_infra//hack:update-deps` updated client-go to an incompatible version.

- The third commit manually updates client-go in repos.bzl with `version = "v0.0.0-20190918200256-06eb1244587a"` and `sum = "h1:huOvPq1vO7dkuw9rZPYsLGpFmyGvy6L8q6mDItgkdQ4="` . These values are taken from the [go.mod](https://github.com/kubernetes/test-infra/blob/70b0b49fe2476f06f97272e77f47ba432cb54244/go.mod#L13) and [go.sum](https://github.com/kubernetes/test-infra/blob/70b0b49fe2476f06f97272e77f47ba432cb54244/go.sum#L689) files in test-infra. Doing this fixed the previous errors and I could also see a call to `EditOrg` in the logs.

/hold
Adding an explicit hold because I'm not sure if manual update to repos.bzl is desired

/assign @fejta @cblecker

### CODE REVIEW

**Comment by nikhita** [comment]
Also, changes to peribolos from the last test-infra version, from `git log --oneline aef6d7642c3b..70b0b49 -- prow/cmd/peribolos`:


```
f9e6647c3 peribolos: correctly calculate if org meta has changed
ed2be029a Add link to Peribolos talk to README
49a5f395d peribolos: Avoid creating archived repos
731383c55 Merge pull request #15151 from petr-muller/repobolos-missing-fields
d65fde4bc Revert "Merge pull request #15320 from stevekuznetsov/skuznets/github-user-agent"
3fa95fc25 Add a version package, populate it and use it
fc496083f peribolos: Error when running --dump without admin:org scope
c7e8573ea github: Addess differences in Repo structures
8b4074163 peribolos: omit repo field with default value from dump
a577147c2 peribolos: dump more repo fields
f1659215a peribolos: Handle renaming corner cases better
fc359ddc5 peribolos: Allow 'change case' renaming
0f6cab24b peribolos: Allow renaming repositories
22f777b41 peribolos: update all allowed repo properties
17b193b0e Make repo archival and publish subject to explicit allow parameter
2828c7175 peribolos: Prevent unsupported API call to unarchive a repo
56ce7ad38 peribolos: Add feature to update existing GitHub repos
9e92239d0 peribolos: Detect repo names duplicate when normalized
0be6cd94c peribolos: basic repo creation functionality
0d8f318a4 peribolos: Dump config data for repositories in the org
210996012 Remove `--job-config-path` option from peribolos
9b609a96d Move prow/{config,plugins}.yaml to config/prow
2869a6863 Actually sync child team repository permissions
f27d286ae Make Prow images that might be used by hand or as PJs put their binary at the FS root.
```

**Comment by nikhita** [comment]
> It looks like this is because bazel run @io_k8s_repo_infra//hack:update-deps updated client-go to an incompatible version.

I can dig more into this later in the week, unless someone gets to it sooner. :)

**Comment by nikhita** [comment]
From a quick look, it looks like it's considering the client-go version in the `require` directive, rather than the `replace` directive.

**Comment by fejta** [comment]
Right, kubernetes does not publish valid client-go versions, requiring the use of a replace in any module that depends on client-go, directly or indirectly.

**Comment by nikhita** [comment]
Closing in favour of https://github.com/kubernetes/org/pull/1500
/close

**Pull request closed without merging**
