### PR TITLE
Update teams.yaml for adding niranjandarshann

### PR DESCRIPTION
**Pull request by niranjandarshann**
@divya-mohan0209  @dipesh-rawat 
The PR www.github.com/kubernetes/website/pull/47782 is merged and raising this for seeking the approval of yours to add my username to the file under hindi reviewer role. 

 /assign @divya-mohan0209  @dipesh-rawat

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for raising this PR. Welcome to the Hindi l10n team.

/lgtm
`/approve` (_Unofficially giving the nod of **approval**; official PR approval can only be applied by sig-docs-leads for changes in this `sig-docs/teams.yaml` file.)_

**Comment by Priyankasaggu11929** [comment]
@niranjandarshann @divya-mohan0209 @dipesh-rawat – checking if PR changes are still needed? If yes, could we please get a formal approve from SIG Docs (Divya :slightly_smiling_face: )? Thanks!

**Comment by divya-mohan0209** [comment]
Approve from my side!
/approve

**Comment by divya-mohan0209** [comment]
Thanks for flagging this @Priyankasaggu11929 ! Welcome to the team, @niranjandarshann :)

**Pull request merged**
