### PR TITLE
Add roycaihw to admin groups in kubernetes-client gen, python and go repos

### PR DESCRIPTION
**Pull request by roycaihw**
Add @roycaihw to the admin groups in 
- kubernetes-client/python
- kubernetes-client/python-base
- kubernetes-client/go
- kubernetes-client/go-base

since I already have admin access to these repos. I maintain the python client repo and do [releases](https://github.com/kubernetes-client/python/releases) regularly.

Also add myself to the admin group in
- kubernetes-client/gen

per conversation in https://github.com/kubernetes-client/gen/pull/97#issuecomment-530034348.

### CODE REVIEW

**Comment by justaugustus** [comment]
Makes sense, but I'll leave it to the current repo admins to approve.
/hold
/assign @brendandburns @mbohlool @yliaog

**Comment by cblecker** [comment]
I've removed your direct admin to these repos, since the groups will cover your access

**Pull request merged**
