### PR TITLE
Add jpbetz to milestone maintainer team

### PR DESCRIPTION
**Pull request by jpbetz**
Need this as TL of API Machinery to opt-in SIG API Machinery KEPs to the current release.

### CODE REVIEW

**Comment by jpbetz** [comment]
@justaugustus could I get an approval on this one?  I need to manage some SIG KEPs.

**Review by justaugustus — APPROVED** [review]
🖖🏽

**Comment by justaugustus** [comment]
Hmmmm... GitHub approve != lgtm here:
/lgtm

**Pull request merged**
