### PR TITLE
Update capi v1.7 release team members

### PR DESCRIPTION
**Pull request by cahillsf**
This PR updates the release team users  for the new Cluster API release v1.7 team.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
@cahillsf can you un-comment my github handle too? I opened PR(https://github.com/kubernetes/org/pull/4586) but it never got merged. I will close mine.

**Comment by cahillsf** [comment]
> @cahillsf can you un-comment my github handle too? I opened PR(#4586) but it never got merged. I will close mine.

@adilGhaffarDev  yep np, just pushed up these changes.  if you are a member of kubernetes org can you also lgtm this PR as appropriate in order to merge?

**Comment by cahillsf** [comment]
> @adilGhaffarDev: changing LGTM is restricted to collaborators
> 
> In response to [this](https://github.com/kubernetes/org/pull/4619#issuecomment-1852036026):
> 
> > /lgtm
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

ah right -- sorry my bad, you would need to be a Reviewer

**Pull request merged**
