### PR TITLE
kubernetes-sigs/sig-api-machinery: add estroz to kubebuilder-admins

### PR DESCRIPTION
**Pull request by estroz**
/cc @DirectXMan12

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Eric's been doing release stuff around the KB-related repos, so having this would be useful (fixing up release notes, etc)

**Review by Aut0R3V — APPROVED** [review]

**Review by nikhita — APPROVED** [review]
Approving based on @DirectXMan12's (member of the admins team + kubebuilder maintainer) comment - https://github.com/kubernetes/org/pull/2419#issuecomment-760513698

/lgtm
/approve

**Pull request merged**
