### PR TITLE
Add dgrisonnet as kube-state-metrics maintainer

### PR DESCRIPTION
**Pull request by dgrisonnet**
/cc @kubernetes/kube-state-metrics-maintainers

### CODE REVIEW

**Comment by mrueg** [comment]
@lilic @brancz @tariq1890 can you help out here and lgtm' this change?

**Review by lilic — COMMENTED** [review]
/lgtm
/approve

/hold
for others to have a look as well :)

**Comment by mrueg** [comment]
@brancz @dashpole @ehashman @logicalhan
can you take a look and help out, looks like we need a sig-instrumentation lead for this change now :)

**Review by ehashman — COMMENTED** [review]
/lgtm
/approve

leaving hold on to give @logicalhan a chance to +1

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

yay!!

**Pull request merged**
