### PR TITLE
Add new SIG Docs co chairs and tech lead to owners aliases

### PR DESCRIPTION
**Pull request by reylejano**
Added new SIG Docs co-chairs and tech lead to sig-docs-leads
See https://github.com/kubernetes/community/blob/master/sig-docs/README.md

cc: @natalisucks @tengqm 

/assign @jimangel @divya-mohan0209

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Lgtm!

**Comment by palnabarun** [comment]
Welcome folks! 🎉 

/approve

**Review by nikhita — APPROVED** [review]
/approve

/woof

**Pull request merged**
