### PR TITLE
Turkish localization team members added.

### PR DESCRIPTION
**Pull request by mkaramuk**
Owners and reviewers of Turkish localization team added.

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
/hold
@mkaramuk have you talked with SIG Docs about creating a new localization group? There are some boostrapping processes they have for new localizations.

You must also be an org member first before being added to any potential groups. :x

**Comment by mkaramuk** [comment]
Do I need a sponsor for it? Because I don't have one :( and I don't think I have most of the requirements. What can I do?

**Comment by mrbobbytables** [comment]
@mkaramuk you do need sponsors - for new localization groups this is usually from the folks in sig-docs who have worked with you to start to stub out the new localization.

**Comment by mkaramuk** [comment]
Ok I will look at it. Thanks.

**Pull request closed without merging**
