### PR TITLE
Adding sig-docs-vi members

### PR DESCRIPTION
**Pull request by truongnh1992**
Owners and reviewers for the Vietnamese translation team
joined at kubernetes/website#16965

Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

### CODE REVIEW

**Comment by zacharysarah** [comment]
@truongnh1992 Agreed 💯 with @nikhita, please limit this PR to yourself and @ngtuna for now. You can add others once they've become members.

**Comment by truongnh1992** [comment]
> The test fails due to:
> 
> ```
> The following members of team sig-docs-vi-reviews are not Kubernetes org members: annp1987, longkb, tiendc
> ```
> 
> IMHO you can add just @ngtuna and yourself for now, and once others start reviewing/sending PRs for Vietnamese localization, we can add them as org members (and eventually to the team).

Thank you @nikhita I've just updated the list.

**Pull request merged**
