### PR TITLE
add self as maintainer for aws-ebs-csi-driver

### PR DESCRIPTION
**Pull request by vdhanan**

### CODE REVIEW

**Comment by AndyXiangLi** [comment]
+1

**Comment by vdhanan** [comment]
@spiffxp

**Comment by vdhanan** [comment]
@nikhita could you please help me get this PR merged? thanks!

**Comment by nikhita** [comment]
/ok-to-test

@vdhanan Hi, we usually ask the SIG leads to approve. In this case, folks in https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-aws/OWNERS should be able to approve. It looks like the list might be slightly stale though...so assigning SIG Cloud Provider leads:

/assign @andrewsykim @cheftako

**Comment by nikhita** [comment]
related - https://github.com/kubernetes/community/issues/5671

**Comment by nikhita** [comment]
Approving based on @cheftako's approve (@cheftako is a SIG Cloud Provider lead)

/approve

**Pull request merged**
