### PR TITLE
Add members 10 02 2020

### LINKED ISSUE #2224: REQUEST: New membership for michaelbeaumont
### GitHub Username
@michaelbeaumont

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@richardcase
@randomvariable 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - [5 PRs contributed, 1 review in `cluster-api-provider-aws`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+involves%3Amichaelbeaumont)
- SIG projects I am involved with
  - sig-cluster-lifecycle

### LINKED ISSUE #2229: REQUEST: New membership for tkashem
### GitHub Username
@tkashem

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @wojtek-t
- @sttts

### List of contributions to the Kubernetes project
- https://github.com/kubernetes/kubernetes/pull/94903 
- https://github.com/kubernetes/kubernetes/pull/94773
- https://github.com/kubernetes/kubernetes/pull/94204
- https://github.com/kubernetes/kubernetes/pull/94134
- https://github.com/kubernetes/kubernetes/pull/88911

### LINKED ISSUE #2234: REQUEST: New membership for @pymander
### GitHub Username
@pymander

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @nikhita 
- @mrbobbytables 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/community/pull/4965
  - https://github.com/kubernetes/community/pull/4967
  - https://github.com/kubernetes/community/pull/5003
  - https://github.com/kubernetes/community/pull/5045
  - https://github.com/kubernetes/community/pull/5091
  - https://github.com/kubernetes-sigs/contributor-site/pull/163
- Issues responded to
- SIG projects I am involved with
  - SIG ContribEx

### LINKED ISSUE #2236: REQUEST: New membership for Jiawei0227
### GitHub Username
Jiawei0227

### Organization you are requesting membership in
kubernetes & kubernetes-csi & kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @msau42 
- @saad-ali 
- @gnufied 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/search?q=org%3Akubernetes+Jiawei0227&type=commits
https://github.com/search?q=org%3Akubernetes-csi+Jiawei0227&type=commits
https://github.com/search?q=org%3Akubernetes-sigs+Jiawei0227&type=commits

- Issues responded to
https://github.com/kubernetes/kubernetes/issues?q=Jiawei0227

- SIG projects I am involved with
sig-storage

### PR DESCRIPTION
**Pull request by ameukam**
Fixes #2224 
Fixes #2229
Fixes #2234
Fixes #2236

### CODE REVIEW

**Comment by ameukam** [comment]
/assign @nikhita @mrbobbytables 
cc @palnabarun @savitharaghunathan

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
