### PR TITLE
membership: Add irvifa to reference-docs-maintainers

### LINKED ISSUE #2227: REQUEST: New membership for @irvifa
### GitHub Username
@irvifa

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
Already member at @kubernetes

### List of contributions to the Kubernetes project
This is related to:
- https://github.com/kubernetes-sigs/reference-docs/pull/171

### PR DESCRIPTION
**Pull request by irvifa**
This should resolve #2227

### CODE REVIEW

**Comment by irvifa** [comment]
Related to https://github.com/kubernetes-sigs/reference-docs/pull/171

**Comment by zacharysarah** [comment]
@irvifa Please add yourself here also:
https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml

**Comment by irvifa** [comment]
@zacharysarah Done 👍

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
