### PR TITLE
Update membership of cloud-provider-vsphere to reflect active maintainers.

### PR DESCRIPTION
**Pull request by randomvariable**
This updates the maintainer list to the current active members for cloud-provider-vsphere.

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

### CODE REVIEW

**Comment by randomvariable** [comment]
cc @lubronzhan

**Comment by nikhita** [comment]
@randomvariable can you also move these teams to https://github.com/kubernetes/org/tree/main/config/kubernetes/sig-cloud-provider?

**Comment by randomvariable** [comment]
> an you also move these teams to https://github.com/kubernetes/org/tree/main/config/kubernetes/sig-cloud-provider?

Can do.

However, do I need to change the group name to fit the convention. It's currently `cloud-provider-vsphere-maintainers` and `cloud-provider-vsphere-admins` but it looks like the convention is `sig-cloud-provider-vsphere-X`.

And if I do do that, I guess there needs to be some remapping of teams in the github repo settings itself and not sure where that's controlled.

**Review by nikhita — COMMENTED** [review]
@randomvariable let's do that as a follow-up.

/approve

Leaving lgtm to @lubronzhan 
/assign @lubronzhan

**Pull request closed without merging**
