### PR TITLE
Update admins and maintainers of KMM

### PR DESCRIPTION
**Pull request by qbarrand**
Remove zvonkok and adrianchiris who contributed to SRO but not to KMM.
Set qbarrand and yevgeny-shnaidman who are the main KMM contributors.

### CODE REVIEW

**Comment by bart0sh** [comment]
@adrianchiris @zvonkok any objections? If not, please lgtm.

**Comment by adrianchiris** [comment]
lgtm, no objections on my end.

**Review by mrunalp — APPROVED** [review]

**Comment by iranzo** [comment]
@dchen1107 @derekwaynecarr is everything fine with this change?

**Comment by derekwaynecarr** [comment]
in case I missed a discussion, is there any discussion on this change from a sig meeting or other setting?

**Comment by SergeyKanzhelev** [comment]
once concern I have is that this change make both contributors be from the same company. I don't think this should block the PR, but I strongly suggest to seek for maintainers from other company.

**Comment by qbarrand** [comment]
@derekwaynecarr this was agreed to at Feb 7th sig-node meeting. Names removed were there from historical reasons (SRO -> KMM) but are not KMM contributors. OK to `/unhold`?

**Pull request merged**
