### PR TITLE
Add members 2024-10-09

### PR DESCRIPTION
**Pull request by ydFu**
This PR:

- Fixed https://github.com/kubernetes/org/issues/5208
- Fixed https://github.com/kubernetes/org/issues/5210

/area github-membership

### CODE REVIEW

**Comment by jasonbraganza** [comment]
/lgtm

/approve

Thank you @ydFu.

**Comment by fanhaouu** [comment]
@jasonbraganza @ydFu Thank you, Master. Sorry to bother you. I have two questions: 
First, as a member, why can't I see my name on the https://github.com/orgs/kubernetes-sigs/people page? 
Second, it seems that I still do not have the 'ok-to-test' permission.

**Comment by jasonbraganza** [comment]
@fanhaouu would you kindly confirm that you received an invite and accepted it? if so then I can run this up the chain and check for you

**Comment by fanhaouu** [comment]
> @fanhaouu would you kindly confirm that you received an invite and accepted it? if so then I can run this up the chain and check for you

Haha, thank you, Master! I just found the invitation link in the email.

**Pull request merged**
