### PR TITLE
Add /me to the patch release and release managers team

### PR DESCRIPTION
**Pull request by hoegaarden**
- I was removed from `patch-release-team` in [this PR][pr], I am not sure why. Re-adding myself again.
- I think I also need to be on `release-managers` to be able to actually cut a patch.

If there are good reasons why I have been removed in the first place, please let me know.

/cc @kubernetes/patch-release-team 
/cc @kubernetes/release-managers 
/cc @cblecker 

[pr]: https://github.com/kubernetes/org/pull/849

### CODE REVIEW

**Comment by cblecker** [comment]
You were removed as only active branch managers or patch release managers should be in these teams. According to the docs in https://git.k8s.io/sig-release, I see you were the 1.14 branch manager, but that release has already shipped.

**Comment by justaugustus** [comment]
@hoegaarden -- I had discussed with @cblecker (via DM) that this change should've been made separately from the changes in that PR, but should've noted that publicly as well.

Christoph --
Approving this as Hannes will be a part of the official roster moving forward: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#contact

/lgtm
/approve

**Comment by cblecker** [comment]
@justaugustus Thanks for the updated docs!

I have two asks:
- When the 1.15 dust settles, would you mind sending out a wider notice of this change? I don't remember seeing one go out to the whole project.
- Can you update the docs to note that if this team changes, you should explicitly reach out to the GitHub admin team? In addition to these teams, there's also things like k-security access that needs to be granted/updated.

**Comment by justaugustus** [comment]
@cblecker -- For sure. I'm actually writing a doc on Release Managers team structure right now.
Stay tuned! :)

**Comment by cblecker** [comment]
@justaugustus You're the best!

**Comment by justaugustus** [comment]
@cblecker -- No, no, you!

**Pull request merged**
