### PR TITLE
Add members 2019-07-17

### LINKED ISSUE #1014: REQUEST: New membership for runyontr
### GitHub Username
@runyontr

### Organization you are requesting membership in
@kubernetes-sigs
@wg-multitenancy 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rjbez17 
- @srampal
- @tashimi

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes/kubernetes/pull/74452
* Issues responded to
   https://github.com/kubernetes-sigs/kubebuilder/issues/675#issuecomment-490875729
   https://github.com/kubernetes/kubernetes/issues/64333
* SIG projects I am involved with
   SIG-Apps
   SIG-Auth (WG-Multitenancy)

### PR DESCRIPTION
**Pull request by nzoueidi**
Fixes #1014 

/area github-membership

### CODE REVIEW

**Comment by nzoueidi** [comment]
Both sponsors are from VMware, holding this PR until another +1 from non-VMware sponsor.
Thanks @mrbobbytables for catching this :D
/hold

**Comment by rjbez17** [comment]
+1 for me

**Comment by nikhita** [comment]
/hold
for second non-vmware sponsor

**Comment by cblecker** [comment]
@nzoueidi can you please rebase instead of using a merge commit?

**Comment by nzoueidi** [comment]
@cblecker looks like there is a conflict when I rebase on top of master. I will resolve it when am at home.

**Comment by mrbobbytables** [comment]
/hold cancel

\o/

**Pull request merged**
