### PR TITLE
Update sig-docs-ja member

### PR DESCRIPTION
**Pull request by nasa9084**
fixed: #2089
Updated teams.yaml according to OWNER_ALIAS on k/website.

https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L116-L127

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@nasa9084 please follow the membership procedure and open the issue using the template first.

You may find more details here - https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by nasa9084** [comment]
@idvoretskyi Hi, Thank you for your comment!
It seems that there is only new membership template but this is not new membership PR.
So I created #2089 without template.

**Comment by idvoretskyi** [comment]
@nasa9084 thanks, I haven't noticed that you are already an org member.

/lgtm

/hold for a final approve by the SIG-Docs team.

**Pull request merged**
