### PR TITLE
Update SIG Instrumentation leads

### PR DESCRIPTION
**Pull request by ehashman**
Removing @piosz, and adding myself and @logicalhan.

/cc @brancz 

See
- https://groups.google.com/d/msg/kubernetes-sig-instrumentation/IZWt4loyx7M/svIYpz0kCwAJ
- https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit

### CODE REVIEW

**Comment by ehashman** [comment]
Oh, this might not be necessary once https://github.com/kubernetes/community/pull/4566 merges? Someone told me to update k8s/org :joy:

**Comment by mrbobbytables** [comment]
> Oh, this might not be necessary once [kubernetes/community#4566](https://github.com/kubernetes/community/pull/4566) merges? Someone told me to update k8s/org 😂

Nope, it is necessary^^;;; they're out of sync --
The other big place to take a look at is k/enhancements and k/k for references to sig-instrumentation-leads

**Comment by ehashman** [comment]
Thanks @mrbobbytables, will TAL

**Pull request merged**
