### PR TITLE
Reduce foot-print of kubernetes-maintainers by removing non-active folks

### PR DESCRIPTION
**Pull request by dims**
Proposal : Better security posture by reducing folks who directly need access to `write` to the main `kubernetes/kubernetes `repository. Picking the following query and using an arbitrary threshold of `100` contributions, leads to reducing the count of people in this group by 7. Still left with 11 people. We also have all the github admins and the sig-release folks, so we are covered.

(Also please see older discussions from https://github.com/kubernetes/org/issues/2332)

Data from `Developer Activity Counts by Companies`
https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=Kubernetes&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=All

(Range: `Last year` and Repository Group: `Kubernetes` and Repository: `kubernetes/kubernetes`)

Date: Monday 20, 2024 (10:30 AM Eastern)

| ID  | From | Contributions |
| ------------- | ------------- | ------------- |
| @apelisse	| Google LLC |	561 |
| @BenTheElder	| Google LLC |	433 |
| @cheftako	| Google LLC |	35 |
| @dchen1107	| Google LLC |	27 |
| @deads2k	    | Red Hat Inc. |	1000 |
| @derekwaynecarr	| Red Hat Inc. |	27 |
| @dims	    | Amazon |	2509 |
| @feiskyer	| Microsoft Corporation |	9 |
| @ingvagabund	| Red Hat Inc. |	25 |
| @janetkuo	| Google LLC |	11 |
| @jingxu97	| Google LLC |	51 |
| @jsafrane	| Red Hat Inc. |	537 |
| @k82cn       | NVIDIA Corporation | 0 |
| @liggitt	    | Google LLC |	4345 |
| @ncdc	    | Red Hat Inc. |	11 |
| @smarterclayton	| Google LLC |	125 |
| @soltysh	    | Red Hat Inc. |	538 |
| @sttts	    | Upbound |	982 |
| @thockin	    | Google LLC |	1961 |
| @wojtek-t	| Google LLC |	1591 |

@derekwaynecarr @feiskyer @ingvagabund @janetkuo @jingxu97 @k82cn @ncdc Please let us know if you continue to need this permission? thanks!

### CODE REVIEW

**Comment by ingvagabund** [comment]
Ok to remove me as well

**Comment by k82cn** [comment]
ok to me, thanks very much :)

**Comment by derekwaynecarr** [comment]
@dims I do not need direct write access to the repo.

**Comment by janetkuo** [comment]
OK for me too!

**Comment by dims** [comment]
thanks everyone who got a chance to respond. If anyone needs us to add this back, we can always reinstate!

/assign @MadhavJivrajani @Priyankasaggu11929 @cblecker 

(assigning to approvers to land this PR. thanks!)

**Review by cblecker — APPROVED** [review]

**Pull request merged**
