### PR TITLE
Added Comms shadows for 1.32

### PR DESCRIPTION
**Pull request by mbianchidev**
Update teams.yaml - Added comms shadows for the 1.32 cycle

### CODE REVIEW

**Comment by gracenng** [comment]
/lgtm
/approve
feel free to tag me as member sponsor as well!

**Comment by mbianchidev** [comment]
Waiting for https://github.com/kubernetes/org/pull/5164

To unhold

**Comment by mbianchidev** [comment]
Unsorted list, my bad, I'll fix it

**Pull request merged**
