### PR TITLE
Renaming Service APIs to Gateway API

### PR DESCRIPTION
**Pull request by robscott**
This accompanies https://github.com/kubernetes-sigs/service-apis/pull/541 and related discussion in https://github.com/kubernetes-sigs/service-apis/issues/536. Not quite sure what the correct order of operations here is.

### CODE REVIEW

**Comment by nikhita** [comment]
@robscott can you create an issue in this repo about the repo name change? The GitHub admins can then rename the repo and ensure that the repo name is updated in all relevant places.

**Comment by robscott** [comment]
Created https://github.com/kubernetes/org/issues/2492, thanks for the tip @nikhita! Let me know if there's anything else I can do for this.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
