### PR TITLE
Updated descriptions for sig-docs-[de|en]-owners

### PR DESCRIPTION
**Pull request by rlenferink**
Using the same description format for all localization teams now.

/cc @zacharysarah 
/assign @nikhita 
/sig docs

### CODE REVIEW

**Comment by rlenferink** [comment]
As our robot suggests ;p
/assign @zacharysarah

**Comment by zacharysarah** [comment]
@rlenferink 👋 Our [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers) for the week is @mistyhacks. 

/assign @mistyhacks

**Comment by zacharysarah** [comment]
I don't think I have permissions either, but:

/approve

**Pull request merged**
