### PR TITLE
Add kayrus to provider-openstack team

### LINKED ISSUE #4056: REQUEST: New membership for kayrus
### GitHub Username

@kayrus

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jichenjc

### Sponsor 2

@zetaab

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/cloud-provider-openstack/pull/2135
- https://github.com/kubernetes/cloud-provider-openstack/pull/2134
- https://github.com/kubernetes/cloud-provider-openstack/pull/1384
- https://github.com/kubernetes/cloud-provider-openstack/pull/1382
- https://github.com/kubernetes/cloud-provider-openstack/pull/1311
- https://github.com/kubernetes/cloud-provider-openstack/pull/1123
- https://github.com/kubernetes/cloud-provider-openstack/pull/1041
- https://github.com/kubernetes/kubernetes/pull/33584

and others...

I'm also an active contributor to https://github.com/gophercloud/gophercloud and https://github.com/terraform-provider-openstack/terraform-provider-openstack

### PR DESCRIPTION
**Pull request by kayrus**
Fixes #4056 

cc @jichenjc @zetaab

### CODE REVIEW

**Comment by kayrus** [comment]
@Priyankasaggu11929 @nikhita kindly ping

**Comment by zetaab** [comment]
I am not in these teams, and I do not know what is purpose of these teams either

**Comment by kayrus** [comment]
according to @nikhita , these teams allow to override tests: https://github.com/kubernetes/org/issues/4056#issuecomment-1453282136

**Comment by Priyankasaggu11929** [comment]
@kayrus, the next here would be to get an approval from one of the exisiting `provider-openstack` team members.

**Comment by kayrus** [comment]
OWNERS file modification in https://github.com/kubernetes/cloud-provider-openstack/ is enough. Closing this PR.

**Pull request closed without merging**
