### PR TITLE
Remove inactive members - Jan 2021

### PR DESCRIPTION
**Pull request by mrbobbytables**
These members have had no activity since July 1st 2019

/github-membership
/hold
/assign @nikhita 

ref #2456

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
/lgtm

@mrbobbytables -- related doubt: we would need to remove the inactive members as well in a follow-up, right? Is there any automated way to do it? Or, just sed through all the instances?

**Comment by mrbobbytables** [comment]
@palnabarun The followup after this is merged is to clean up the owners files, this can still go in ahead of time though.

**Comment by nikhita** [comment]
/lgtm cancel

@mrbobbytables should we revert the recent change due to https://github.com/kubernetes/org/issues/2456#issuecomment-767594729?

**Comment by mrbobbytables** [comment]
> @mrbobbytables should we revert the recent change due to #2456 (comment)?
Yes, I just re-added the commit

**Review by nikhita — APPROVED** [review]
/lgtm

**Pull request merged**
