### PR TITLE
Add dipesh-rawat to sig-docs-en-reviews

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Add dipesh-rawat to sig-docs-en-reviews

Ref: https://github.com/kubernetes/website/pull/41627

/cc @sftim @reylejano @natalisucks @tengqm

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@sftim @tengqm @reylejano @natalisucks Hey, just a friendly ping here. Would it be possible to provide some feedback on this in order to make progress?

**Comment by sftim** [comment]
Hi @dipesh-rawat 

Why should we make this change?

Thank you for suggesting that you become a reviewer; can you outline why that's the right thing for us - Kubernetes project - to do?

**Comment by dipesh-rawat** [comment]
> Hi @dipesh-rawat
> 
> Why should we make this change?
> 
> Thank you for suggesting that you become a reviewer; can you outline why that's the right thing for us - Kubernetes project - to do?


@sftim Thanks for taking time to look into this request. As mentioned in the referenced https://github.com/kubernetes/website/pull/41627, I have actively participated in the review process, working on and engaging with incoming issues and PRs. By including me as a reviewer, we would bring in fresh perspectives and contribute to diversifying the pool of reviewers, ultimately benefiting the overall review process and fostering the growth of the community. I am confident in my ability to continue providing valuable assistance. 
However, I completely understand that it may not be currently feasible to add me as a reviewer due to either insufficient enagegement or the lack of need for new reviewers. In that case, I am more than happy to close the PRs raised and apologize for any inconvenience caused. I would appreciate any feedback that can help me work towards becoming a reviewer in the future.

**Comment by sftim** [comment]
Thanks. I'll run this past my colleagues.

**Comment by dipesh-rawat** [comment]
> Thanks. I'll run this past my colleagues.

Hey @sftim, Just wanted to check in and see if you had a chance to discuss my request with your colleagues. If there's any progress or updates, I'd love to hear about it. Thanks for your time in considering the matter and I'm looking forward to hearing from you soon!

**Comment by sftim** [comment]
:+1: from me

Thanks

**Comment by reylejano** [comment]
at this time, @dipesh-rawat has reviewed about 280+ PRs and authored 16 merged PRs to k/website
@dipesh-rawat has offered helpful suggestions in some of @dipesh-rawat's reviews

👍 from me
/approve

**Pull request merged**
