### PR TITLE
Add jihoon-seo to sig-docs-ko-owners

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Add @jihoon-seo to sig-docs-ko-owners.
- related with kubernetes/website#31206

### CODE REVIEW

**Comment by seokho-son** [comment]
As the SIG-Docs Korean l10n team lead, I am really happy with this PR !
@jihoon-seo is one of the most active contributors for Korean l10n.

**Comment by sftim** [comment]
/lgtm
/approve
/hold
for https://github.com/kubernetes/website/pull/31206

**Comment by sftim** [comment]
@jihoon-seo thanks very much for your contributions so far, and for stepping forward

**Pull request merged**
