### PR TITLE
Add fabriziopandini to CAPV GitHub admins and maintainers

### PR DESCRIPTION
**Pull request by fabriziopandini**
Just noticed that I forgot to add me in this groups

cc @sbueringer @chrigl

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
the owner file needs a cleanup, unless i'm mistaken?
/lgtm
/hold
(pls, unhold when see fit)

**Comment by sbueringer** [comment]
Which owner file?

**Comment by neolit123** [comment]
teams file for CAPV, my mistake.

**Comment by neolit123** [comment]
> teams file for CAPV, my mistake.

well, this OWNERs file too i guess:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/OWNERS_ALIASES

**Comment by fabriziopandini** [comment]
/hold cancel
We can bring up cleanup during the next CAPV office hours

**Pull request merged**
