### PR TITLE
Add members 2022-08-22

### LINKED ISSUE #3390: REQUEST: New membership for phuongatemc
### GitHub Username

phuongatemc

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xing-yang

### Sponsor 2

@yuxiangqian

### List of contributions to the Kubernetes project

- I've been active in the Data Protection Working Group
- I am one of the authors of the DP Working Group's White Paper  https://github.com/kubernetes/community/blob/master/wg-data-protection/data-protection-workflows-white-paper.md
- I am currently working on the Changed Block Tracking proposal in the DP Working Group https://hackmd.io/VN_TBl3NSLaeiD8BLeeCfw and CBT weekely syncup Meeting notes: https://docs.google.com/document/d/19ExU8VCIEYhmOFeYs2NtWoA13iG7Sp0RvrXpyvmE-fE/edit#
- I am also contributing to Velero's features such as Backup ResourceOrder etc.  https://github.com/vmware-tanzu/velero/pull/2724

### LINKED ISSUE #3608: REQUEST: New membership for pbetkier
### GitHub Username

@pbetkier

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mwielgus

### Sponsor 2

@gjtempleton

## PRs
* e2e: Fix ResourceConsumer unstable request interval [#108104](https://github.com/kubernetes/kubernetes/pull/108104)
* Add e2e test for HPA behavior: decreased downscale stabilization [#108264](https://github.com/kubernetes/kubernetes/pull/108264)
* Fix comment in HPA's scale event replicaChange [#111463](https://github.com/kubernetes/kubernetes/pull/111463)
* Add sig-autoscaling as owners of test/e2e/framework/autoscaling [#108702](https://github.com/kubernetes/kubernetes/pull/108702)

## Reviews
* Add e2e HPA Behavior tests: scale up/down limited by number of Pods / min, scale up/down limited by percentage / min [#111346](https://github.com/kubernetes/kubernetes/pull/111346#pullrequestreview-1047965863)
* Add e2e HPA Behavior tests: scale down stabilisation, scale up disabled, scale down disabled [#111253](https://github.com/kubernetes/kubernetes/pull/111253#pullrequestreview-1044608850)
* Add e2e test for HPA behavior: scale up delay [#110385](https://github.com/kubernetes/kubernetes/pull/110385#pullrequestreview-1004234675)
* Only log requests for configured consumptions in ResourceConsumer [#109231](https://github.com/kubernetes/kubernetes/pull/109231#pullrequestreview-930229913)
* Add e2e test for HPA behavior: scale up and down disabled [#110386](https://github.com/kubernetes/kubernetes/pull/110386#pullrequestreview-1011824084)

## Issues
* Increase fallback consumption for HPAs with target over 100% [#111433](https://github.com/kubernetes/kubernetes/issues/111433)

### LINKED ISSUE #3614: REQUEST: New membership for Volatus
### GitHub Username

@Volatus

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@strongjz

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

`PRs Authored`
- https://github.com/kubernetes/ingress-nginx/pull/8877
- https://github.com/kubernetes/ingress-nginx/pull/8859
- https://github.com/kubernetes/ingress-nginx/pull/8812
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2724
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2714
- https://github.com/kubernetes-sigs/external-dns/pull/2857

`Issues engaged with`
- https://github.com/kubernetes/ingress-nginx/issues/8874
- https://github.com/kubernetes/ingress-nginx/issues/8828
- https://github.com/kubernetes/ingress-nginx/issues/8824
- https://github.com/kubernetes/ingress-nginx/issues/8823
- https://github.com/kubernetes/ingress-nginx/issues/8745
- https://github.com/kubernetes/ingress-nginx/issues/8702
- https://github.com/kubernetes-sigs/external-dns/issues/2780

### LINKED ISSUE #3623: REQUEST: New membership for negz
### GitHub Username

@negz

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@apelisse

### Sponsor 2

@sttts

### List of contributions to the Kubernetes project

Full set: https://github.com/search?l=&p=3&q=org%3Akubernetes+author%3Anegz&type=Issues

Some more interesting ones:

* https://github.com/kubernetes/autoscaler/pull/462
* https://github.com/kubernetes/kubernetes/pull/110820
* https://github.com/kubernetes/kubernetes/pull/111559
* https://github.com/kubernetes/kubernetes/issues/111880

### LINKED ISSUE #3627: REQUEST: New membership for ArkaSaha30
### GitHub Username

ArkaSaha30

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsors

- @palnabarun
- @Arhell
- @matthyx
- @saschagrunert 

### List of contributions to the Kubernetes project

> Issues engaged with
- https://github.com/kubernetes/test-infra/issues/25806 
- https://github.com/kubernetes/website/issues/34174
- https://github.com/kubernetes/release/issues/2549
- https://github.com/kubernetes-sigs/bom/issues/114
- https://github.com/kubernetes/test-infra/issues/26614

> PRs authored
- https://github.com/kubernetes/test-infra/pull/26796
- https://github.com/kubernetes/website/pull/34175
- https://github.com/kubernetes/release/pull/2552
- https://github.com/kubernetes-sigs/bom/pull/115
- https://github.com/kubernetes-sigs/bom/pull/119

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Fixes #3390 
Fixes #3608 
Fixes #3614 
Fixes #3623 
Fixes #3627

cc @palnabarun @ameukam 

/hold for review

### CODE REVIEW

**Comment by Sea-n** [comment]
LGTM too.

Fix date format to [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339.html).
/retitle Add members 2022-08-22

**Comment by palnabarun** [comment]
/lgtm
/approve

/hold cancel

Thank you @savitharaghunathan ! 🙏🏽

**Pull request merged**
