### PR TITLE
Add sayanchowdhury as the milestone maintainer

### PR DESCRIPTION
**Pull request by sayanchowdhury**
/cc @kubernetes/release-team-leads
/cc @bai
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>

### CODE REVIEW

**Review by bai — APPROVED** [review]

**Comment by bai** [comment]
/lgtm

Glad to have you on the team!

**Comment by palnabarun** [comment]
/lgtm

Welcome to the team @sayanchowdhury! :tada:

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
/assign @tpepper 

(for approval)

**Pull request merged**
