### PR TITLE
sig apps: add team repo permissions for lws repo

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
Ref: https://github.com/kubernetes/org/issues/4737

/assign @kubernetes/sig-apps-leads 

cc: @kubernetes/owners

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
@ahg-g, I'm unable to add @liurupeng username to the GH teams atm.

They will need to apply for [org membership](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) first, for the tool to allow adding their GH username to teams.

**Comment by ahg-g** [comment]
> @ahg-g, I'm unable to add @liurupeng username to the GH teams atm.
> 
> They will need to apply for [org membership](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) first, for the tool to allow adding their GH username to teams.

sounds good, we can add Rupeng later once he gets his membership.

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve
/hold

Feel free to remove hold when ready!

**Comment by Priyankasaggu11929** [comment]
Thank you all

/unhold

**Pull request merged**
