### PR TITLE
Add richabanker to sig-instrumentation-leads

### PR DESCRIPTION
**Pull request by richabanker**
Issue: https://github.com/kubernetes/community/issues/8149

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by Priyankasaggu11929** [comment]
/approve

/hold
(please unhold, if ready to merge. Thank you :slightly_smiling_face: )

**Comment by Priyankasaggu11929** [comment]
Ping @richabanker, @logicalhan – checking if we're fine removing the hold here? :slightly_smiling_face:

**Comment by richabanker** [comment]
@Priyankasaggu11929 yeah I think we should be good to unhold.
/unhold

**Pull request merged**
