### PR TITLE
Require org members to be sorted

### PR DESCRIPTION
**Pull request by fejta**
/assign @cblecker @spiffxp @nikhiljindal 

a) Do we want to enforce this (we already enforce the absence of duplicates)
b) Do we want to enforce case sensitive sorting?

### CODE REVIEW

**Comment by spiffxp** [comment]
/lgtm
I am fine with this

**Comment by cblecker** [comment]
Enforcing sorting: 👍
Enforcing case sensitive sorting: 👎

Main thought behind that, is the dump from peribolos doesn't dump in case sensitive sorting (I'm guessing that's simply the way GitHub returns results). We also "normalize" case in a lot of places, so I'd like to ignore case wherever possible.

**Comment by fejta** [comment]
PTAL, now require sorting to be case insensitive

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

🎉 🚀 🚢

**Comment by nikhita** [comment]
/unassign @nikhiljindal 

lgtm :+1:

**Pull request merged**
