### PR TITLE
Add lzhecheng to cloud-provider-azure-admins

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

### CODE REVIEW

**Comment by palnabarun** [comment]
@lzhecheng -- you need to request for an org membership request first before you can add yourself to any team. See the org membership requirements [here](https://github.com/kubernetes/community/blob/master/community-membership.md).

**Comment by lzhecheng** [comment]
@palnabarun hello, I have created an membership request issue before. Here is the link: https://github.com/kubernetes/org/issues/3242#issuecomment-1039748085

Thank you!

**Review by feiskyer — COMMENTED** [review]
/approve

**Pull request merged**
