### PR TITLE
Add astoycos to NPAPI admins

### PR DESCRIPTION
**Pull request by astoycos**
astoycos is an owner in the
adminNetworkPolicy API repo
and should be added here as
well.

Related to https://github.com/kubernetes/org/issues/3643

### CODE REVIEW

**Comment by astoycos** [comment]
cc @rikatz @abhiraut

**Comment by rikatz** [comment]
Lgtm
Andrew is the fact npapi admin and I guess I can even stepdown on this :)

**Review by rikatz — APPROVED** [review]

**Pull request merged**
