### PR TITLE
Update teams.yaml to address remaining changes for the v1.28 release cycle

### PR DESCRIPTION
**Pull request by Atharva-Shinde**
Changed teams.yaml to add new shadows and remove-update enhancements group of previous cycle

### CODE REVIEW

**Comment by mrbobbytables** [comment]
please ignore this - I'm testing something quick

/ok-to-test

**Comment by palnabarun** [comment]
@Atharva-Shinde -- can you please resolve the merge conflicts on this?

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve

**Comment by MadhavJivrajani** [comment]
/hold
Please ping once conflicts are resolved.

**Comment by Atharva-Shinde** [comment]
Looks like most of the work that this PR intended was merged with the PR mentioned above: #4210. This PR now addresses remaining changes.

**Comment by Atharva-Shinde** [comment]
^@palnabarun @MadhavJivrajani

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

/hold cancel

**Pull request merged**
