### PR TITLE
Add some bazel and hack rules

### PR DESCRIPTION
**Pull request by fejta**
Once these are checked in I can add presubmit jobs for this repo

/assign @calebamiles @spiffxp @cblecker

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

🚀

**Comment by fejta** [comment]
Some concerns about excess nosiness around the `set -o xtrace` and we may want to remove these later but can be a follow up PR

**Comment by fejta** [comment]
/hold cancel

Thanks for the review!

**Pull request merged**
