### PR TITLE
Rename `k8s.io/test-infra` module to `sigs.k8s.io/prow`

### PR DESCRIPTION
**Pull request by jihoon-seo**
Recently, Prow has been moved from https://github.com/kubernetes/test-infra to https://github.com/kubernetes-sigs/prow, its exclusive repo.

This PR applies Prow module path updates by renaming `k8s.io/test-infra` module to `sigs.k8s.io/prow`.

@cjwagner Please take a look, as one of Prow OWNERS!

### CODE REVIEW

**Review by cjwagner — APPROVED** [review]

**Comment by jihoon-seo** [comment]
/assign @cblecker
(as per https://github.com/kubernetes/org/pull/4890#issuecomment-2071275268)

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve
/hold 
Holding in case any last comments/changes, pls feel free to remove when you see fit!

**Comment by jihoon-seo** [comment]
@MadhavJivrajani @cjwagner Thank you!
I am going to unhold:
/unhold

**Pull request merged**
