### PR TITLE
Add ehashman to sig-instrumentation

### PR DESCRIPTION
**Pull request by ehashman**
Follow-up to #993/#994.

/cc @brancz @piosz

### CODE REVIEW

**Comment by ehashman** [comment]
Sigh. I've been having major issues with getting the CLA to register as signed since switching employers, and apparently https://github.com/cncf/gitdm/pull/153 didn't fix it. Will try to get some help with this.

**Comment by ehashman** [comment]
Submitted [SUPPORT-285](https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-285) to the LF JIRA to try to figure out what's wrong with the CLA.

**Comment by brancz** [comment]
Welcome! :tada: 

/lgtm
/approve

**Pull request merged**
