### PR TITLE
updating SIG Docs co-chairs

### PR DESCRIPTION
**Pull request by jimangel**
Updating SIG Docs chairs.

Ref: https://github.com/kubernetes/website/issues/29354

/cc @parispittman @sftim

### CODE REVIEW

**Comment by sftim** [comment]
/lgtm

/hold
so we can make the relevant updates in a batch of sorts
/approve

**Comment by parispittman** [comment]
I don't think I can approve here but trying anyway

/approve
/hold cancel

**Comment by cblecker** [comment]
'approve

**Review by cblecker — APPROVED** [review]

**Pull request merged**
