### PR TITLE
Update teams.yaml

### PR DESCRIPTION
**Pull request by yodahekinsew**
Need admin access in order to add issues to the k8s-container-image-promoter repo

### CODE REVIEW

**Comment by justaugustus** [comment]
@yodahekinsew -- No one requires admin access to our repos to file issues. You can file issues on that repo through this link: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/new

Was there something specific you were looking for information about or was this a privilege escalation attempt?

cc: @kubernetes/release-engineering @kubernetes/owners 
/close

**Comment by yodahekinsew** [comment]
I'm working under @listx for the summer as a Google intern and maintainer of the CIP repo, and need admin access to the Container Image Promoter so that I can create and close issues as well as projects.

**Comment by justaugustus** [comment]
Got it! I'm chatting with Linus now.

**Comment by listx** [comment]
@yodahekinsew Can you first go through the motions to become a member of kubernetes-sigs? https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E

**Pull request closed without merging**
