### PR TITLE
Add German language team members

### PR DESCRIPTION
**Pull request by bene2k1**
Add German speaking team members for documentation

### CODE REVIEW

**Comment by zacharysarah** [comment]
@bene2k1 Thanks for following up on https://github.com/kubernetes/website/pull/13340#discussion_r268336019. It looks like you need to be a Kubernetes org member before we can approve this PR. Please [open a new issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) requesting membership. I’m happy to sponsor you as a new contributor to German localization. You’ll need to find one more—maybe @mrbobbytables?

**Comment by sieben** [comment]
@zacharysarah I've stepped up. @bene2k1 is a colleague so I will help him

**Pull request merged**
