### PR TITLE
Add members 2019-02-13

### LINKED ISSUE #472: REQUEST: New membership for sieben
### GitHub Username

@sieben 

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @zacharysarah 
- @Smana 

### List of contributions to the Kubernetes project

I work with for sig-docs on the French localization of the Kubernetes project.

https://github.com/kubernetes/website/pull/12548

### LINKED ISSUE #475: REQUEST: New membership for lledru
### GitHub Username
@lledru
### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij 
- @zacharysarah 

### List of contributions to the Kubernetes project
- SIG-Release/enhancement: shadow 1.14
- SIG-Docs: I work with for sig-docs on the French localization of the Kubernetes project.

### LINKED ISSUE #476: REQUEST: New membership for @AWKIF
### GitHub Username
@AWKIF

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @yastij
* @zacharysarah

### List of contributions to the Kubernetes project
* SIG-Release/enhancement: shadow 1.14
* SIG-Docs: I work with for sig-docs on the French localization of the Kubernetes project.

### LINKED ISSUE #477: REQUEST: New membership for perriea
### GitHub Username
@perriea

### Organization you are requesting membership in
@kubernetes

### Requirements
* [x]  I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
* [x]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
* [x]  I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
* [x]  I am actively contributing to 1 or more Kubernetes subprojects
* [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
* @zacharysarah
* @Smana 

### List of contributions to the Kubernetes project
I would like to contribute on the  sig-docs on the French localization of the Kubernetes project.
[kubernetes/website#12636](https://github.com/kubernetes/website/pull/12636)
[kubernetes/website#12548](https://github.com/kubernetes/website/pull/12548)

### LINKED ISSUE #478: REQUEST: New membership for rbenzair
### GitHub Username
@rbenzair

### Organization you are requesting membership in
(at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ ] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @yastij  
- @Smana

### List of contributions to the Kubernetes project
- I would like to contribute on the  sig-docs on the French localization of the Kubernetes project.
- Contribute on the Chaos Eng Working Group

### LINKED ISSUE #480: REQUEST: New membership for jichenjc
### GitHub Username
jichenjc

note: I requested membership at https://github.com/kubernetes/org/issues/389 and forgot to add kubernetes-sig..so open this issue to handle that part 

### Organization you are requesting membership in
kubernetes-sig

### Requirements
- [ x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x ] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of contributions to the Kubernetes project
[kubernetes/cloud-provider-openstack#411](https://github.com/kubernetes/cloud-provider-openstack/pull/411)
[kubernetes/cloud-provider-openstack#398](https://github.com/kubernetes/cloud-provider-openstack/pull/398)
[kubernetes/cloud-provider-openstack#397](https://github.com/kubernetes/cloud-provider-openstack/pull/397)
[kubernetes/cloud-provider-openstack#380](https://github.com/kubernetes/cloud-provider-openstack/pull/380)
[kubernetes/cloud-provider-openstack#379](https://github.com/kubernetes/cloud-provider-openstack/pull/379)

[kubernetes-sigs/cluster-api-provider-openstack#148](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/148)

### PR DESCRIPTION
**Pull request by mrbobbytables**
fixes #472 
fixes #475 
fixes #476 
fixes #477 
fixes #478 
fixes #480 

/area github-membership

### CODE REVIEW

**Comment by justaugustus** [comment]
@mrbobbytables -- tests failed on sorting

**Comment by mrbobbytables** [comment]
Had sieben in the wrong spot, fixing now will force push in a sec.

**Comment by mrbobbytables** [comment]
There we go.

**Pull request merged**
