### PR TITLE
commenting in daniel chan now that his org request is approved.

### PR DESCRIPTION
**Pull request by drewhagen**
I just remembered - we choose to comment him out to get the other shadows set up. 

cc @chanieljdan

### CODE REVIEW

**Comment by fsmunoz** [comment]
Hi!

/lgtm

**Comment by drewhagen** [comment]
@fsmunoz Thanks for catching this! I appreciate it

**Comment by fsmunoz** [comment]
@puerco I think this is good to go, could you approve it? Thanks!

**Comment by drewhagen** [comment]
@puerco @jeremyrickard Is someone available to approve this? I appreciate it! I will bring attention to this in the RT meeting today.

**Review by puerco — APPROVED** [review]

**Comment by puerco** [comment]
Done!

**Pull request merged**
