### PR TITLE
add hankang to sig-instrumentation teams.yaml

### PR DESCRIPTION
**Pull request by logicalhan**
/cc @brancz @piosz

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@logicalhan did you mean to `hankang` instead of your github handle? 😬

**Comment by logicalhan** [comment]
> Han Kang did you mean to `hankang` instead of your github handle? 😬

🤦‍♂️ yes, I did. I seem to have forgotten my github handle.

**Comment by mrbobbytables** [comment]
1 last thing :x 

the lists need to be alphabetically sorted.

**Comment by logicalhan** [comment]
> 1 last thing :x
> 
> the lists need to be alphabetically sorted.

Oh, yeah I just saw the failing test. It actually wasn't sorted previously. But fixed now :)

**Comment by cblecker** [comment]
Please squash your commits :)

**Comment by logicalhan** [comment]
> Please squash your commits :)

Sure thing. Thanks!

**Comment by cblecker** [comment]
lgtm from a github admin pov

/assign @brancz @piosz 
for approval from the sig

**Comment by brancz** [comment]
Overdo if you ask me ;)

/lgtm

**Comment by brancz** [comment]
Thanks! :)

**Pull request merged**
