### PR TITLE
Update admins for cloud-provider-vsphere

### PR DESCRIPTION
**Pull request by andrewsykim**
Adding new folks who have been actively contributing and removing folks who are no longer active.

Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

### CODE REVIEW

**Review by dvonthenen — APPROVED** [review]

**Comment by nikhita** [comment]
@andrewsykim can you move this team to https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-cloud-provider/teams.yaml so that you can approve any changes directly in the future? :)

**Review by nikhita — APPROVED** [review]
Approving this, let's restructure the teams in a follow-up.

/lgtm
/approve

**Pull request merged**
