### PR TITLE
Add cluster-api-provider-packet-admins and maintainers teams

### PR DESCRIPTION
**Pull request by gianarb**
Related to the submission to move cluster-api-provider-packet to
kubernetes-sigs https://github.com/kubernetes/org/issues/1934

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
until repo is created

**Comment by nikhita** [comment]
@gianarb the tests are failing due to a bazel flake, retesting after sometime should fix the flake.

For the tests to pass, all team members also need to members of the kubernetes-sigs org so the jobs will only be green once everyone has been added as members.

**Comment by justaugustus** [comment]
/retitle Add cluster-api-provider-packet-admins and maintainers teams

**Comment by nikhita** [comment]
@gianarb thank you!!

/lgtm
/approve

/hold cancel
everything is ready for the migration, will do in a bit

**Pull request merged**
