### PR TITLE
Adding liggitt and dims to client-go repo

### PR DESCRIPTION
**Pull request by dims**
We need to do some surgery in the client-go repo, working through steps in https://github.com/kubernetes/kubernetes/issues/98267

### CODE REVIEW

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
```
--- FAIL: TestAllOrgs (0.06s)
    config_test.go:251: The team client-go-maintainers in org Kubernetes has an unsorted list of members
    config_test.go:251: The team client-go-admins in org Kubernetes has an unsorted list of members
```

I'll @dims sort that out

**Comment by dims** [comment]
> 
> I'll @dims sort that out

Hehehe

**Review by spiffxp — APPROVED** [review]
/approve

**Comment by cblecker** [comment]
lgtm when sorted lol

**Comment by BenTheElder** [comment]
humansort is the worst sort

**Comment by nikhita** [comment]
@dims @liggitt ping on this :)

**Comment by dims** [comment]
think we are done with the client-go and didn't need this :)

/close

**Pull request closed without merging**
