### PR TITLE
Add nitishfy to kubernetes-sigs org

### PR DESCRIPTION
**Pull request by nitishfy**
- Reference: https://github.com/kubernetes/org/issues/4494#issuecomment-1742147606

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by mrbobbytables** [comment]
/hold
It should be a single commit with this as the commit message: Add nitishify to kubernetes-sigs ort

Sorry,  in my original reply the < > were meant to mean a variable.

**Comment by nitishfy** [comment]
@mrbobbytables Ready to be approved!

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/approve
/hold cancel

**Pull request merged**
