### PR TITLE
Add Joe Betz to kubernetes-sigs

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by lavalamp** [comment]
Surprising that this is separate.

**Comment by apelisse** [comment]
Yeah, there's massive duplication between kubernetes-sigs and kubernetes directory.

**Comment by cblecker** [comment]
It's something contribex is working on :)

/lgtm
/approve

**Comment by apelisse** [comment]
Awesome, thanks @cblecker !

**Comment by apelisse** [comment]
@cblecker Would you happen to know what we're missing here: https://github.com/kubernetes-sigs/structured-merge-diff/pull/135#issuecomment-564776668

Thanks!

**Comment by cblecker** [comment]
@apelisse Joe needs to accept the invitation (either the link he received via e-mail, or by visiting https://github.com/kubernetes-sigs)

**Comment by apelisse** [comment]
Thank you @cblecker !

**Pull request merged**
