### PR TITLE
Addmembers 08-28-2020 

### LINKED ISSUE #2146: REQUEST: New membership for hickeyma
### GitHub Username
@hickeyma

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @saschagrunert 
- @feiskyer 

### List of contributions to the Kubernetes project
- PRs reviewed / authored:
  - https://github.com/kubernetes-sigs/cri-tools/pull/594
  - https://github.com/kubernetes-sigs/cri-tools/pull/595
  - https://github.com/kubernetes-sigs/cri-tools/pull/598
  - https://github.com/kubernetes-sigs/cri-tools/pull/599
  - https://github.com/kubernetes-sigs/cri-tools/pull/604
  - https://github.com/kubernetes-sigs/cri-tools/pull/606
  - https://github.com/kubernetes-sigs/cri-tools/pull/607
  - https://github.com/kubernetes-sigs/cri-tools/pull/611
  - https://github.com/kubernetes-sigs/cri-tools/pull/615
  - https://github.com/kubernetes-sigs/cri-tools/pull/623
  - https://github.com/kubernetes-sigs/cri-tools/pull/630
  - https://github.com/kubernetes-sigs/cri-tools/pull/631
  - https://github.com/kubernetes-sigs/cri-tools/pull/634
  - https://github.com/kubernetes-sigs/cri-tools/pull/635
  - https://github.com/kubernetes-sigs/cri-tools/pull/641
  - https://github.com/kubernetes-sigs/cri-tools/pull/647
  - https://github.com/kubernetes-sigs/cri-tools/pull/648
  - https://github.com/kubernetes-sigs/cri-tools/pull/626
  - https://github.com/kubernetes-sigs/cri-tools/pull/622
  - https://github.com/kubernetes-sigs/cri-tools/pull/603
  - https://github.com/containerd/cri/pull/1457
  - https://github.com/kubernetes/community/pull/4720
- Issues responded to:
  - https://github.com/kubernetes-sigs/cri-tools/issue/592
  - https://github.com/kubernetes-sigs/cri-tools/issue/597
  - https://github.com/kubernetes-sigs/cri-tools/issue/639
  - https://github.com/kubernetes-sigs/cri-tools/issue/613
  - https://github.com/kubernetes-sigs/cri-tools/issue/608
  - https://github.com/kubernetes-sigs/cri-tools/issue/605
  - https://github.com/kubernetes-sigs/cri-tools/issue/602
- SIG projects I am involved with:
  - https://github.com/kubernetes-sigs/cri-tools

### LINKED ISSUE #2149: REQUEST: New membership for gabbifish
### GitHub Username
@gabbifish

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock 
- @camilamacedo86

### List of contributions to the Kubernetes project
- Wrote envtest docs for the kubebuilder project, so people can get a more general intro to envtest
  - Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1518
  - PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1521
- Reviewed kubebuilder project PRs:
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1569
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1570
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1571
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1623
  - https://github.com/kubernetes-sigs/kubebuilder/pull/1626
- Issues opened/investigating:
  - https://github.com/kubernetes/kubernetes/issues/94313

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Fixes #2146 
Fixes #2149 

/hold

(holding for closing more requests in a batch)

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
cc: @palnabarun @ameukam 

/assign @nikhita @mrbobbytables

**Comment by hickeyma** [comment]
Delighted to become a member. Thank you @palnabarun and @mrbobbytables for review. Thank you @savitharaghunathan for setting up review and merge.

**Pull request merged**
