### PR TITLE
Add prksu to kubernetes-sigs org

### PR DESCRIPTION
**Pull request by prksu**
Fixes https://github.com/kubernetes/org/issues/1725

I'm already member of kubernetes org and this PR is to request access to kubernetes-sig I've been working in `cluster-api-provider-digitalocean` project.

/cc @xmudrii @cpanato

### CODE REVIEW

**Comment by prksu** [comment]
fixes https://github.com/kubernetes/org/issues/1725

**Comment by nikhita** [comment]
Btw thanks for helping out with the cluster-api-do project :)

**Comment by prksu** [comment]
You’re welcome :grin:

**Pull request merged**
