### PR TITLE
Add new members (7/22/19)

### PR DESCRIPTION
**Pull request by justaugustus**
Fixes: #1029, fixes: #1028, fixes: #1027, fixes: #1026, fixes: #1023, fixes: #1030

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@justaugustus runyontr still doesn't have a 2nd non-vmware sponsor 😬

**Comment by justaugustus** [comment]
@mrbobbytables -- thanks for catching. Did not realize the other +1 was not an owner.
Just dropped the commit and we can handle in #1017.

**Comment by mrbobbytables** [comment]
Thanks! \o/
moooarrr release shadows~
/lgtm
/approve

**Pull request merged**
