### PR TITLE
Add kfox1111 to wg-multitenancy

### PR DESCRIPTION
**Pull request by kfox1111**
---
name: Organization Membership Request
about: Request membership in a Kubernetes Org
title: 'REQUEST: New membership for kfox1111'
labels: area/github-membership
assignees: ''"

---

### GitHub Username
kfox1111

### Organization you are requesting membership in
kubernetes-sigs/sig-auth

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rjbez17
- @dims 

### List of contributions to the Kubernetes project
* Helped with the ephemeral csi storage spec / implementation
* Implemented the initial ephemeral implementation in csi-driver-host-path
* Implemented the csi-driver-image-populator driver

### CODE REVIEW

**Comment by rjbez17** [comment]
@kfox1111 you also need to add your self to the kubernetes-sig org: https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/org.yaml

**Comment by rjbez17** [comment]
I support @kfox1111's membership

/approve

**Comment by tashimi** [comment]
/approve

tenor-63337610

**Comment by dims** [comment]
+1 from me

**Comment by mrbobbytables** [comment]
Hey there @kfox1111 If you could, please file an issue for org member to join @kubernetes-sigs. Org membership itself should be handled separately (in its own commit) from being added to a team.

Membership in @kubernetes lets you request membership in any of the "child" or "sub" orgs without requiring further sponsorship, but the inverse relationship is not the case. As you're strictly a member of @kubernetes-csi further sponsorship is needed. =/ 

The child or sub-org memberships are strictly scoped to their orgs and are not available for cross-org membership without further approval.

I know this can be kind of confusing, so if you have any questions please don't hesitate to ask or ping in slack.

Thanks!


/hold

**Comment by tashimi** [comment]
@kfox1111 sorry for the confusion, it turns out you don't need to join this group to join the repo -- I've updated our readme to explain the process here: https://github.com/kubernetes-sigs/multi-tenancy

So we can close this one for now, we just need the other PR you have open to be approved for membership into kubernetes-sigs

**Comment by kfox1111** [comment]
Ok, so what I need to do is amend this pr to only ask for org membership, not team membership?

**Comment by mrbobbytables** [comment]
@kfox1111 As we have support from 2 sponsors here, I think if you just update your PR to add yourself to k-sigs and not the maintainer list that should be fine. The commit message should be:

`Add kfox1111 to kubernetes-sigs org.`

**Comment by kfox1111** [comment]
Ok. I think I did that. Please let me know if I messed something up.

**Pull request merged**
