### PR TITLE
add davidgamero to javascript-admins teams

### PR DESCRIPTION
**Pull request by davidgamero**
add davidgamero to javascript-admins teams

### CODE REVIEW

**Comment by brendandburns** [comment]
@davidgamero has been contributing to the repo for a while and having a single admin is not scalable, adding him will help with maintaining the repo.

**Comment by Priyankasaggu11929** [comment]
Hello @brendandburns, we'll need your GH username added as a Kubernetes GitHub org member first before this PR changes.

Could you please create a New Org Membership Request issue following this [template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)? Thanks!

**Comment by Priyankasaggu11929** [comment]
/hold for Kubernetes org membership.

@brendandburns, could you please update the commit message as well to describe the PR changes (i.e `add davidgamero to javascript-admins teams`) . Thank you!

**Comment by davidgamero** [comment]
@Priyankasaggu11929 thank you I've updated the commit message, merge main and submitted the org request

**Comment by davidgamero** [comment]
updated with correct ordering for org test

**Comment by davidgamero** [comment]
@Priyankasaggu11929 looks like the other PR went through, so this one should be able to be unblocked now that i'm an org member

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
