### PR TITLE
Add benmoss to sig-windows-tools maintainers

### PR DESCRIPTION
**Pull request by benmoss**
@PatrickLang @michmike

### CODE REVIEW

**Comment by PatrickLang** [comment]
a bit of context on this - Ben is planning to mark releases as some of the kubeadm work for alpha & beta releases are completed. That way people an download a zip/tarball instead of doing a git clone when they're trying it out

**Comment by cblecker** [comment]
If you just need to cut releases, `-maintainers` is sufficient. Also, the lists need to be alpha sorted

**Comment by benmoss** [comment]
Switched to just maintainers and made it sorted

**Comment by justaugustus** [comment]
Can we edit the PR title to match?

**Pull request merged**
