### PR TITLE
Adding AravindhP as maintainter to sig-windows-tool repo

### PR DESCRIPTION
**Pull request by marosset**
Also removing dougland 

/sig windows
/assign @aravindhp @jsturtevant @knabben

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
@marosset should we update sig-windows-dev-tools-admins also?

**Comment by marosset** [comment]
> @marosset should we update sig-windows-dev-tools-admins also?

Yea, i'll do that now

**Pull request merged**
