### PR TITLE
Add bburns to openapi perl admin/write

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by rlenferink** [comment]
/lgtm

As Brendan Burns is core maintainer for the k8s-client projects.

**Comment by nikhita** [comment]
While we are here, can you also add Brendan to the python repos? Ref: https://github.com/kubernetes/org/pull/622#issuecomment-477597199

**Comment by yue9944882** [comment]
@nikhita no problem, added python

**Comment by yue9944882** [comment]
wow you are reactive!

**Pull request merged**
