### PR TITLE
Add Members 2021-08-18

### LINKED ISSUE #2871: REQUEST: New membership for arahamad
### GitHub Username

arahamad

### Organization you are requesting membership in

kubernetes, kubernetes-client, kubernetes-csi

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mrbobbytables

### Sponsor 2

spzala

### List of contributions to the Kubernetes project

- PRs reviewed / authored

100+ PR reviewed for many repos under https://github.com/IBM
50+ PR author for many repos under https://github.com/IBM
Couple of PR owner on https://github.com/kubernetes-csi listing IBM VPC block CSI driver kubernetes-csi/docs#346

- Issues responded to

Created some issues for CSI sidecars VA issues
csi-node-driver-registrar:v2.0.1 image having VA issues kubernetes-csi/node-driver-registrar#121
csi-provisioner:v2.0.4 image has VA issues kubernetes-csi/external-provisioner#528
livenessprobe:v2.1.0 image has VA issues kubernetes-csi/livenessprobe#92
csi-attacher:v3.1.0 image having VA issues kubernetes-csi/external-attacher#307
csi-resizer:v1.0.0 image having VA issues kubernetes-csi/external-resizer#154

- SIG projects I am involved with

https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver
https://github.com/kubernetes-csi

### LINKED ISSUE #2875: REQUEST: New membership for LochanRn
### GitHub Username

LochanRn

### Organization you are requesting membership in
kubernetes-sigs

### Requirements

- [x]  I have reviewed the community membership guidelines
- [x]  I have enabled 2FA on my GitHub account
- [x]  I have subscribed to the kubernetes-dev e-mail list
- [x]  I am actively contributing to 1 or more Kubernetes subprojects
- [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] OPTIONAL: I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
### Sponsor 1

@CecileRobertMichon

### Sponsor 2

@nader-ziada

### List of contributions to the Kubernetes project

- PRs reviewed / authored
[Availability zones support for managed clusters](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1564)
[Azure active directory support for managedclusters](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1560)
[Added support for system node pools in managedClusters](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1520)
[fix deletion for azureManagedControlPlane while using existing RG](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1442)
[Adds additional tags to aks cluster managed by capz](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1393)
[Capz should not add tags to managed resource group](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1218)
[🐛fix for vpc deletion failure](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2327)
🌱 Updated Bastion node's AMI. Changed the OS version to Ubuntu 20.04 from Ubuntu 16.04](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2068)

- Issues created/responded to
[Provide availability zones support in managedclusters](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1559)
[Documentation about jobs that run during e2e test cases](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1497)
[Add AAD Support for AKS](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1407)
[While updating agentPools need to check for only fields which are mutable.](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1536)
[AzuremanagedControlPlane stuck while deletion when using non capz managed RGs](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1441)
[Update containerservice sdk API version from 2020-02-01 to 2021-05-01](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1418)
[Unable to cleanly delete an AKS managed cluster by capz](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1395)

- SIG projects I am involved with
[cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure)

### LINKED ISSUE #2892: REQUEST: New membership for shaneutt
### GitHub Username

@shaneutt

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@robscott

### Sponsor 2

@hbagdi

### List of contributions to the Kubernetes project

currently working on:
- https://github.com/kubernetes-sigs/gateway-api/issues/708
- https://github.com/kubernetes-sigs/gateway-api/issues/708
- https://github.com/kubernetes-sigs/gateway-api/pull/786

previously worked on:
- https://github.com/kubernetes-sigs/kubebuilder/issues/2165
- https://github.com/kubernetes-sigs/kind/issues/2143
- https://github.com/kubernetes-sigs/kind/issues/2136
- https://github.com/kubernetes-sigs/kind/issues/732
- https://github.com/kubernetes-sigs/kustomize/issues/847
- https://github.com/kubernetes-sigs/kubebuilder/issues/571
- https://github.com/kubernetes/kubernetes/issues/76671

- https://github.com/kubernetes-sigs/gateway-api/pull/715
- https://github.com/kubernetes-sigs/gateway-api/pull/565
- https://github.com/k8snetworkplumbingwg/multus-cni/pull/555
- https://github.com/kudobuilder/kudo/pull/1488
- https://github.com/istio/istio.io/pull/7155
- https://github.com/kubernetes/community/pull/4661
- https://github.com/kubernetes-sigs/kind/pull/733
- https://github.com/kudobuilder/kudo/pull/201
- https://github.com/kubernetes-sigs/kustomize/pull/845
- https://github.com/kubernetes-sigs/kubebuilder/pull/574
- https://github.com/kubernetes-sigs/kubebuilder/pull/572

### LINKED ISSUE #2895: REQUEST: New membership for anubha-v-ardhan
### GitHub Username

@anubha-v-ardhan

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes-dev e-mail list](https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sftim

### Sponsor 2

@nikhita

### List of contributions to the Kubernetes project

> ### `hi` localization
>> #### Tracking Issue
>>> https://github.com/kubernetes/website/issues/29353
>> #### My PRs
>>> https://github.com/kubernetes/website/pull/29373
>>> https://github.com/kubernetes/website/pull/29374
>>> https://github.com/kubernetes/website/pull/29413
>>> https://github.com/kubernetes/website/pull/29376
>>> https://github.com/kubernetes/website/pull/29396
>>> https://github.com/kubernetes/website/pull/29399
>>> https://github.com/kubernetes/website/pull/29403
>>> https://github.com/kubernetes/website/pull/29412
>> #### PRs I reviewed or I am reviewing 
>>> https://github.com/kubernetes/website/pull/29383
>>> https://github.com/kubernetes/website/pull/29420
>>> https://github.com/kubernetes/website/pull/29407
>>> https://github.com/kubernetes/website/pull/29416
>>> https://github.com/kubernetes/website/pull/29434
>>> and more .....
> ### Currently working on (other than `hi` localization)
>> https://github.com/kubernetes/website/pull/28720
>> https://github.com/kubernetes/community/issues/4469 ("Meet our contributors" blog series for APAC region)
> ### Previously worked on:
>> https://github.com/kubernetes/website/pull/28920
>> https://github.com/kubernetes/website/pull/28850
>> https://github.com/kubernetes/website/pull/28961
>> https://github.com/kubernetes/k8s.io/issues/1597

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #2871 
fixes #2875 
fixes #2892 
fixes #2895

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold
Remove hold when ready.

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/hold cancel
/woof

**Comment by anubha-v-ardhan** [comment]
Thank you : )

**Pull request merged**
