### PR TITLE
Add David Vossel as cluster-api-provider-kubevirt admin/maintainer

### PR DESCRIPTION
**Pull request by davidvossel**
I'm one of the primary contributors to the cluster-api-provider-kubevirt project. We'd like to spread the ownership of the repo out a little bit further and I've volunteered to help there. I'll need the ability to create tags/releases as well as manage secrets for CI.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@davidvossel thanks for submitting this addition.
@agradouski @cchengleo is admin access required for @davidvossel ?

/approve
/hold

(LGTM / remove hold if see fit)

**Comment by agradouski** [comment]
@neolit123 yes, please add @davidvossel to admins of `cluster-api-provider-kubevirt` repo. we have discussed this with the group in capk community meetings, and all in agreement. it's required to help with repo secrets manipulations for automated workflows that david and his team are working on, going forward. thanks
/lgtm
/approve

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold cancel
/ok-to-test

**Comment by davidvossel** [comment]
@neolit123 can i get another lgtm? My name wasn't in alphabetic order and failed the test. i just updated the commit to fix that.

**Comment by neolit123** [comment]
sure!

/lgtm

**Pull request merged**
