### PR TITLE
Add 1.30 Docs Shadows to GitHub teams

### PR DESCRIPTION
**Pull request by drewhagen**
#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
Add 1.30 Docs Shadows to sig-docs and sig-release teams

/assign @katcosgrove @gracenng @neoaggelos @ramrodo @sanchita-07 @fsmunoz

### CODE REVIEW

**Comment by sanchita-07** [comment]
We need to create an issue in `kubernetes/org` repository requesting membership for @chanieljdan in kubernetes org.

**Comment by fsmunoz** [comment]
Hi @drewhagen, the entries should be in alphabetical order (I'm suggesting changes on that)

>The following members of team website-milestone-maintainers are not Kubernetes org members: chanieljdan

The corresponding membership request needs to be opened and approved before this can be merged.

**Comment by drewhagen** [comment]
@fsmunoz Thanks for the reminder! I pushed a commit to alphabetize the shadows and I reached out to Daniel about registering for the K8s org.

**Comment by reylejano** [comment]
job failed because @chanieljdan is not a Kubernetes org member

@drewhagen , you can add @chanieljdan in a later PR when @chanieljdan is an org member or wait until @chanieljdan is an org member

**Comment by drewhagen** [comment]
Here is the issue requesting membership:
https://github.com/kubernetes/org/issues/4699

I'll take y'all's advice of opening another PR while waiting

**Review by justaugustus — APPROVED** [review]

**Pull request merged**
