### PR TITLE
re-add fabriziopandini to milestone maintainers

### PR DESCRIPTION
**Pull request by neolit123**
original request was here, pre-prune:
https://github.com/orgs/kubernetes/teams/kubernetes-milestone-maintainers/discussions/5

/assign @tpepper @fabriziopandini 
cc @timothysc @luxas

### CODE REVIEW

**Comment by luxas** [comment]
/lgtm
I'll let someone else approve.

**Comment by fabriziopandini** [comment]
thanks @luxas and @neolit123, I'm happy to help!

**Comment by justaugustus** [comment]
SGTM!
/lgtm
/approve

**Pull request merged**
