### PR TITLE
Add anthonydahanne

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
ping @remyleone @rbenzair ! Thank you !

**Comment by remyleone** [comment]
:+1:

**Comment by remyleone** [comment]
I think you have to open an issue.

**Comment by anthonydahanne** [comment]
yes @remyleone indeed; here it is: https://github.com/kubernetes/org/issues/1320

thanks!

**Comment by nzoueidi** [comment]
Thank you @anthonydahanne for opening the issue. It has been addressed in this PR #1321.

/close

**Pull request closed without merging**
