### PR TITLE
Add members 09-23-2020 part 3

### LINKED ISSUE #2208: REQUEST: New membership for srm09
### GitHub Username
@srm09

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @vincepri 
- @CecileRobertMichon 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  * https://github.com/kubernetes-sigs/cluster-api/pull/3508
  * https://github.com/kubernetes-sigs/cluster-api/pull/3166
  * https://github.com/kubernetes-sigs/cluster-api/pull/3164
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/639
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/658

- Issues responded to
  * https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+assignee%3Asrm09
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/561
  * https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/557

- SIG projects I am involved with
  * kubernetes-sigs/cluster-api
  * kubernetes-sigs/cluster-api-provider-azure

### LINKED ISSUE #2216: REQUEST: New membership for tanjacky
### GitHub Username
@tanjacky

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @JamesLaverack 
- @lachie83

### List of contributions to the Kubernetes project
Release Notes Shadow for 1.20

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Fixes #2208 
Fixes #2216 

cc: @palnabarun @ameukam

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
/hold
(for a few hours for more membership requests)

/assign @mrbobbytables @nikhita

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
