### PR TITLE
Add everpeace to sig-scheduling teams

### PR DESCRIPTION
**Pull request by everpeace**
fixes: #1173

### CODE REVIEW

**Comment by nikhita** [comment]
These teams are used for notification means (pinging sig-scheduling-feature-requests on a PR/issue to get their attention). These teams don't have any effect on approval. Approval is carried out using OWNERS files only. 

However, it might make sense to reconcile both the corresponding OWNERS_ALIASES and GitHub teams. Example - people in sig-scheduling-api-reviews should be same in the OWNERS_ALIASES file and the GitHub team.

**Comment by everpeace** [comment]
@draveness I removed me from `sig-scheduling-api-reviews` as nikhita's comments. 

Please take a look.

**Comment by draveness** [comment]
> These teams are used for notification means (pinging sig-scheduling-feature-requests on a PR/issue to get their attention). These teams don't have any effect on approval. Approval is carried out using OWNERS files only.
> 
> However, it might make sense to reconcile both the corresponding OWNERS_ALIASES and GitHub teams. Example - people in sig-scheduling-api-reviews should be same in the OWNERS_ALIASES file and the GitHub team.

@nikhita, do you have any suggestions on how to deal with this kind of PR? The sig scheduling file was only edited by you and @cblecker. I searched through the repo and didn't find any similar cases. Is it necessary to keep syncing this with kubernetes `OWNERS_ALIAS`?

> @draveness I removed me from `sig-scheduling-api-reviews` as nikhita's comments.
> 
> Please take a look.

/hold
Thanks, I'd like to hold this PR for now and wait for clarification on the usage and management of the file.

**Comment by k82cn** [comment]
/close

Some people will help to fix #1173 with PR, e.g. Bob; we only need to open membership request by issue.

If we want to add/update reviewers/approver, please open PR in k/k against `OWNERS_ALIAS`.

> These teams are used for notification means (pinging sig-scheduling-feature-requests on a PR/issue to get their attention). These teams don't have any effect on approval. Approval is carried out using OWNERS files only.

IMO, that should be ok to only contain reviewers/approvers of sigs of those team :)

**Comment by draveness** [comment]
> @nikhita , IMO, that should be ok to only contain reviewers/approvers of sigs of those team :)

+1

**Pull request closed without merging**
