### PR TITLE
replace mszostok with jhvhs as sig-service-catalog chair

### PR DESCRIPTION
**Pull request by jberkhahn**
Mateusz is leaving the project. We've selected Konstantin as the new co-chair

@mszostok 
@jhvhs

### CODE REVIEW

**Comment by mszostok** [comment]
Hi @jberkhahn thanks for taking care of that! 🙇 

here is also pr for our community https://github.com/kubernetes/community/pull/5228

**Comment by nikhita** [comment]
/hold
until https://github.com/kubernetes/community/pull/5228 merges

**Review by idvoretskyi — APPROVED** [review]
/approve

**Comment by idvoretskyi** [comment]
/hold cancel

https://github.com/kubernetes/community/pull/5228 is merged.

**Pull request merged**
