### PR TITLE
Script to apply declared config

### PR DESCRIPTION
**Pull request by fejta**
Plus other initial infrastructure

/assign @spiffxp @cblecker 

Primarily supporting the following:
```shell
bazel test //config:all  # Test all the various config/kubernetes-foo orgs
bazel run //admin:update # Run peribolos on all the files
```

Docs at https://github.com/fejta/org/blob/infra/admin/README.md

### CODE REVIEW

**Comment by fejta** [comment]
/approve
🙄

**Comment by cblecker** [comment]
/hold

Because we don't have CI in this repo yet, I want to review this closely before merge. Thanks for doing this!

**Comment by fejta** [comment]
Sure I can also move the vendor (or any of the other commits) into their own PRs if that helps. 

Also I can start setting up ci after this goes in. 


We are adding all the verify-boilerplate etc stuff

**Comment by fejta** [comment]
ping

**Comment by fejta** [comment]
FYI moved the first two commits into https://github.com/kubernetes/org/pull/27

**Comment by fejta** [comment]
okay this is now ready to go and < 500 LOC

**Pull request merged**
