### PR TITLE
Adding Ravi as a member for wg-structured-logging

### PR DESCRIPTION
**Pull request by ravitri**
Adding `ravitri` github user as a member for wg-structured-logging

### CODE REVIEW

**Comment by shubheksha** [comment]
Hi @ravitri I think you need to be a K8s org member to be added to the list

**Comment by ravitri** [comment]
@shubheksha - Thanks a lot! Yeah, the logs of failed job show that but I checked it for existing members and they aren't part of the Kubernetes org too. Difference is, I don't have commits to other k8s repos yet and this is my first k8s project. Well, I can follow the issues via issue filters for now and subscribe to them manually. I think there are certain requirements to be part of kubernetes org and I don't think I qualify for it yet so can close this request. Can raise again in near future.

**Comment by serathius** [comment]
Hey @ravitri, feel free to reach out on #wg-structured-logging slack channel. Will try to help with joining the org.

**Pull request closed without merging**
