### PR TITLE
Adding sig-docs-vi members

### PR DESCRIPTION
**Pull request by huynguyennovem**
Add new owner and reviewer for the Vietnamese translation team

Signed-off-by: Nguyen Quang Huy <huynguyennovem@gmail.com>

### CODE REVIEW

**Comment by truongnh1992** [comment]
/lgtm
@huynguyennovem joined the owners and reviewers for the Vietnamese translation team at kubernetes/website#17653

**Comment by zacharysarah** [comment]
@huynguyennovem Please wait for #1375 to merge, then rebase this PR and add members to `website-maintainers` instead of to `sig-docs-l10n-admins`.

**Comment by huynguyennovem** [comment]
> @huynguyennovem Please wait for #1375 to merge, then rebase this PR and add members to `website-maintainers` instead of to `sig-docs-l10n-admins`.

Yes, I have done this.

**Pull request merged**
