### PR TITLE
Prune k-maintainers list

### PR DESCRIPTION
**Pull request by liggitt**
Dropping folks from the list with write access to create new k/k branches who have been inactive in the repo in the past year, or rotated out, or I verified did not need the access

### CODE REVIEW

**Comment by liggitt** [comment]
cc @brendandburns @fejta @justinsb @lavalamp @mikedanese @mtaufen @mwielgus @spiffxp @tallclair

**Comment by mtaufen** [comment]
Thanks. Hopefully blocks me from making [mistakes](https://github.com/kubernetes/kubernetes/pull/121724) with the GitHub web UI again :).

**Comment by justinsb** [comment]
Lgtm.. thanks for doing this

**Review by cblecker — APPROVED** [review]
Thank you to all for your contributions to Kubernetes!

**Pull request merged**
