### PR TITLE
Add sig-instrumentation members

### PR DESCRIPTION
**Pull request by RainbowMango**
Welcome, all of you:
- @dashpole 
- @lilic
- @s-urbaniak
- @RainbowMango 
- @tariq1890

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Thank you @RainbowMango ! :heart: I guess this effectively supersedes #1650 ?

**Comment by RainbowMango** [comment]
Oh...Sorry, I haven't noticed your PR.

**Comment by lilic** [comment]
Thanks! 🎉

**Comment by logicalhan** [comment]
/lgtm

🎉🎉😃😃

**Comment by brancz** [comment]
We still have to prune the list a bit as well, we need to look at individual ones though. Let’s do that in a separate one.

/lgtm
/approve

**Pull request merged**
