### PR TITLE
add mstruebing as javascript client admin

### PR DESCRIPTION
**Pull request by mstruebing**
Add me as an admin for the javascript client so I can help maintain the repository by merging PRs and creating releases

### CODE REVIEW

**Comment by brendandburns** [comment]
As with #4548 this will help us with maintainence of the javascript repo and @mstruebing has already been contributing a bunch.

**Comment by Priyankasaggu11929** [comment]
Hello @mstruebing , we'll need your GH username added as a Kubernetes GitHub org member first before this PR changes.

Could you please create a New Org Membership Request issue following this [template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E)? Thanks!

**Pull request merged**
