### PR TITLE
Add SataQiu to milestone maintainers team

### PR DESCRIPTION
**Pull request by SataQiu**
Request to join milestone maintainers team for Docs (Chinese).

Looking forward to your support  @zacharysarah !

### CODE REVIEW

**Comment by zacharysarah** [comment]
@kubernetes/sig-docs-zh-owners Please review.

**Comment by SataQiu** [comment]
Thanks @tengqm @zacharysarah 
ping @tpepper
PTAL. Thanks :)

**Comment by SataQiu** [comment]
Emm @justaugustus I think it is not contradictory. I have more responsibility in Docs(Chinese), so I choose to submit my application as a Docs maintainer.  In addition to Docs，I am also actively participating in some other areas, such as e2e framework refactor、golint/staticcheck/shellcheck failures fix and something related to cluster-life-cycle(such as kubeadm). If I can mark milestones, it will help me better deal with the relevant PRs.

**Comment by justaugustus** [comment]
@SataQiu --

> I am also actively participating in some other areas, such as e2e framework refactor、golint/staticcheck/shellcheck failures fix and something related to cluster-life-cycle(such as kubeadm)

Right, so the work that you do in k/k seems to suggest this should have approval from leadership in SIG Testing or SIG Cluster Lifecycle.

The reason I was trying to get clarification on the Docs side is because we weren't adding Docs approvers to `milestone-maintainers`, outside of those that are working on the Release Team. That would be a policy change and would then require us to add all Docs approvers to `milestone-maintainers`, which I don't think is the goal here.

Details on `milestone-maintainers` membership can be found here: https://github.com/kubernetes/sig-release/tree/master/release-team#milestone-maintainers

SIG Testing or Cluster Lifecycle Chairs/TLs (@justinsb, @timothysc, @fejta, @spiffxp, @stevekuznetsov) --
Can you approve @SataQiu's membership as a milestone maintainer for your SIG?

**Comment by cblecker** [comment]
Milestone maintainer rights for most folks are attached to a SIG and that SIGs priorities. For example, a milestone maintainer for Docs should not be tagging PRs into the milestone for sig network/testing/etc.

For the `hack/` and `test/` directories, I don't think we need any additional milestone maintainers. There isn't much that is in those directories that we need to push through a freeze (outside of coordination with sig-release).

**Comment by SataQiu** [comment]
ok, thanks for your explanation.
/close

**Comment by cblecker** [comment]
@SataQiu if you do see something that you think needs to be tagged, please feel to ping me or one of the other testing/contribex leads

**Pull request closed without merging**
