### PR TITLE
Adding jmrodri and varshaprasad96 to KB admins

### PR DESCRIPTION
**Pull request by jmrodri**
Signed-off-by: jesus m. rodriguez <jesusr@redhat.com>

### CODE REVIEW

**Comment by camilamacedo86** [comment]
/ok-to-test
/lgtm
/approved

@pwittrock @mrbobbytables as we spoke about @varshaprasad96 and @jmrodri they will step in as admin as well to help us a little more with the project. Thank you for your help and support :-)

**Review by camilamacedo86 — APPROVED** [review]

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Pull request merged**
