### PR TITLE
add nilekhc and salaxander to secrets-store-csi-driver maintainers

### PR DESCRIPTION
**Pull request by aramase**
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>

/assign @tam7t @ritazh 
/cc @nilekhc @salaxander

### CODE REVIEW

**Comment by aramase** [comment]
/hold

for reviews

**Comment by ritazh** [comment]
+1

**Comment by palnabarun** [comment]
/lgtm
/approve

@ritazh's +1 should be sufficient here since @ritazh is in `sig-auth-leads`

https://github.com/kubernetes/org/blob/b98f9b1029b8e5adabec7c08713bd8c7f20cf72a/OWNERS_ALIASES#L14-L19

PS: Changes to files inside `config/<org>/<sig>` don't require approval from GitHub Admins. The OWNERS in those directories can themselves LGTM and Approve.

**Comment by palnabarun** [comment]
@aramase @ritazh Please feel to remove the hold whenever you want. :)

**Comment by aramase** [comment]
thanks @palnabarun! We're also going to discuss in the secrets-store-csi-driver community call next week. I'll remove the `/hold` if there are no concerns after that.

**Comment by mrbobbytables** [comment]
Is there a reason the hold is still in place? Can this be merged?

**Pull request merged**
