### PR TITLE
Add `cri-client` staging repository

### PR DESCRIPTION
**Pull request by saschagrunert**
Per: https://github.com/kubernetes/org/issues/4805

cc @kubernetes/sig-node-leads

### CODE REVIEW

**Comment by dims** [comment]
+1 from me

**Comment by saschagrunert** [comment]
Changed to `cri-client` per https://github.com/kubernetes/org/issues/4805#issuecomment-2078756671

**Comment by saschagrunert** [comment]
I think we got approval in https://github.com/kubernetes/org/issues/4805#issuecomment-2079794253 and https://github.com/kubernetes/org/issues/4805#issuecomment-2080233298. 

PTAL OWNERS @cblecker @MadhavJivrajani @mrbobbytables @nikhita @palnabarun @Priyankasaggu11929

**Pull request merged**
