### PR TITLE
Add Members 2022-08-11

### LINKED ISSUE #3583: REQUEST: New membership for azylinski
### GitHub Username

@azylinski

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marseel

### Sponsor 2

@shyamjvs

## kubernetes

Always log APF WorkEstimate params in kube-apiserver http logs
https://github.com/kubernetes/kubernetes/pull/111109

Add audit-id to all traces
https://github.com/kubernetes/kubernetes/pull/110680

Fix requests scope classification; cherry picked to v1.21..v1.24
https://github.com/kubernetes/kubernetes/pull/110009

Cleanup: Remove unused lastContainerStartedTime time.Cache lru
https://github.com/kubernetes/kubernetes/pull/111289

Issue reported: Junit files too large to parse, causing blank testgrid
https://github.com/kubernetes/kubernetes/issues/111510

## perf-tests

Update CL2 APIResponsivenessPrometheus threasholds
https://github.com/kubernetes/perf-tests/pull/2080

Grafana comparison dashboard
https://github.com/kubernetes/perf-tests/pull/2022

## community

Update "API call latency SLIs/SLOs details" definition
Inc objective for read-only requests in "namespace" scope: from 5s to 30s
https://github.com/kubernetes/community/pull/6601

### LINKED ISSUE #3586: REQUEST: New membership for pawbana
### GitHub Username

pawbana

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marseel

### Sponsor 2

@shyamjvs

## kubernetes
Added requestSloLatencies metric
https://github.com/kubernetes/kubernetes/pull/105890
https://github.com/kubernetes/kubernetes/pull/106306

## test-infra
Added and used prow job annotation setting 'base_options' tab option
https://github.com/kubernetes/test-infra/pull/24731
https://github.com/kubernetes/test-infra/pull/24735
https://github.com/kubernetes/test-infra/pull/24762

## perf-tests
Added parsing of generic Pantheon queries results to perfdash
https://github.com/kubernetes/perf-tests/pull/1992

### LINKED ISSUE #3588: REQUEST: New membership for knelasevero
### GitHub Username

@knelasevero

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@damemi

### Sponsor 2

@ingvagabund

### PRs involved in (created/reviewed):
https://github.com/kubernetes-sigs/descheduler/pull/888
https://github.com/kubernetes-sigs/descheduler/pull/852
https://github.com/kubernetes-sigs/descheduler/pull/854
https://github.com/kubernetes-sigs/descheduler/pull/871
https://github.com/kubernetes-sigs/descheduler/pull/860
https://github.com/kubernetes-sigs/descheduler/pull/895
https://github.com/kubernetes-sigs/descheduler/pull/861
https://github.com/kubernetes-sigs/descheduler/pull/892
https://github.com/kubernetes/kubernetes/pull/111155

### Issues:
https://github.com/kubernetes-sigs/descheduler/issues/845
https://github.com/kubernetes/kubernetes/issues/111672
https://github.com/kubernetes/kubernetes/issues/91633
https://github.com/kubernetes-sigs/descheduler/issues/884
https://github.com/kubernetes-sigs/descheduler/issues/844
https://github.com/kubernetes-sigs/descheduler/issues/837

### SIGs I am involved with:
sig-scheduling

CC: @damemi @ingvagabund

### LINKED ISSUE #3594: REQUEST: New membership for muyangren2
### GitHub Username

muyangren2

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@neolit123

### Sponsor 2

@aojea

### List of contributions to the Kubernetes project

- PRs reviewed / authored
   https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Amuyangren2
- Issues responded to
  https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+commenter%3Amuyangren2
- SIG projects I am involved with
  kubernetes/kubernetes

### LINKED ISSUE #3597: REQUEST: New membership for <bishal7679>
### GitHub Username

@bishal7679

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@divya-mohan0209

### Sponsor 2

@mehabhalodiya

### PRs Authored:
- [kubernetes/website#34725](https://github.com/kubernetes/website/pull/34725)
- [kubernetes/website#34657](https://github.com/kubernetes/website/pull/34657)
- [kubernetes/website#34936](https://github.com/kubernetes/website/pull/34936)
- [kubernetes/website#34847](https://github.com/kubernetes/website/pull/34847)
- [kubernetes/website#34750](https://github.com/kubernetes/website/pull/34750)
- [kubernetes/website#35315](https://github.com/kubernetes/website/pull/35315)
### PRs I have reviewed:
- [kubernetes/website#34826](https://github.com/kubernetes/website/pull/34826)
- [kubernetes/website#34772](https://github.com/kubernetes/website/pull/34772)
- [kubernetes/website#34766](https://github.com/kubernetes/website/pull/34766)
- [kubernetes/website#34760](https://github.com/kubernetes/website/pull/34760)
#### Subproject I'm contributing to: Kubernetes/website

### LINKED ISSUE #3598: REQUEST: New membership for yibozhuang
### GitHub Username

@yibozhuang

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@wzshiming

### List of contributions to the Kubernetes project

- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/105196
  - https://github.com/kubernetes/kubernetes/pull/109715
  - https://github.com/kubernetes/kubernetes/pull/105245
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/408
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/344

- Issues responded to
  - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/302
  - https://github.com/kubernetes/kubernetes/issues/109876

- SIG projects I am involved with
  - sig-scheduling
  - sig-storage

### LINKED ISSUE #3600: REQUEST: New membership for BenjaminKazemi
### GitHub Username

@BenjaminKazemi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@BenTheElder

### Sponsor 2

@dims

### List of contributions to the Kubernetes project

- https://github.com/kubernetes/test-infra/pull/27008

### LINKED ISSUE #3602: REQUEST: New membership for mimowo
### GitHub Username

@mimowo

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@alculquicondor

### Sponsor 2

@soltysh

### List of contributions to the Kubernetes project

PRs authored:
https://github.com/kubernetes/kubernetes/pull/110292
https://github.com/kubernetes/kubernetes/pull/111070
https://github.com/kubernetes/kubernetes/pull/111084
https://github.com/kubernetes/kubernetes/pull/111091
https://github.com/kubernetes/kubernetes/pull/110959
https://github.com/kubernetes/kubernetes/pull/111113

https://github.com/kubernetes/enhancements/pull/3374
https://github.com/kubernetes/enhancements/pull/3438
https://github.com/kubernetes/enhancements/pull/3447

https://github.com/kubernetes/website/pull/35219

PRs reviewed:
https://github.com/kubernetes/kubernetes/pull/110294
https://github.com/kubernetes/kubernetes/pull/111475

Issues created:
https://github.com/kubernetes/kubernetes/issues/111140
https://github.com/kubernetes/kubernetes/issues/111183
https://github.com/kubernetes/kubernetes/issues/111308
https://github.com/kubernetes/kubernetes/issues/111612
https://github.com/kubernetes/kubernetes/issues/111614

### LINKED ISSUE #3604: REQUEST: New membership for Shubham82
### GitHub Username

@Shubham82

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@gjtempleton

### Sponsor 2

@jihoon-seo

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  https://github.com/search?q=is%3Apr+author%3Ashubham82++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- Issues responded to
  https://github.com/search?q=commenter%3Ashubham82++org%3Akubernetes+org%3Akubernetes-sigs&type=Issues
- SIG projects I am involved with
  sig-auth
  sig-autoscaling

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #3583
fixes #3586
fixes #3588
fixes #3594
fixes #3597
fixes #3598
fixes #3600
fixes #3602
fixes #3604

/area github-membership

### CODE REVIEW

**Comment by mimowo** [comment]
Please add #3602 to the list of issues fixed.

**Comment by palnabarun** [comment]
@mimowo -- my edits to the PR comment were in draft while I had to leave for a work meeting. :)

**Comment by ameukam** [comment]
/lgtm
/hold 

remove the hold when ready

**Pull request merged**
