### PR TITLE
Add RainbowMango as a milestone maintainer for sig instrumentation

### PR DESCRIPTION
**Pull request by RainbowMango**
Request to be added as a milestone maintainer for sig instrumentation.

/cc @brancz

### CODE REVIEW

**Comment by brancz** [comment]
I don't think I can solely approve this, but this has my approval as sig instrumentation lead.

**Comment by RainbowMango** [comment]
> I don't think I can solely approve this, but this has my approval as sig instrumentation lead.

Thanks.  We are following the standard process.
According to [the process](https://github.com/kubernetes/sig-release/tree/master/release-team#milestone-maintainers)
1. get an approver from sigs
2. Then, assign to SIG Release Chair for final approval.

/assign @tpepper

**Pull request merged**
