### PR TITLE
Add members 20210924

### PR DESCRIPTION
**Pull request by mrbobbytables**
fixes: #2975
fixes: #2976
fixes: #2983 
fixes: #2986
fixes: #2993 
fixes: #2994
fixes: #2995
fixes: #3000

/area github-membership

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

Thanks Bob 💖

**Comment by mrbobbytables** [comment]
/hold

just for a few to double check something

**Comment by mrbobbytables** [comment]
/hold cancel
fixed it 👍 could use another lgtm

**Review by kundan2707 — COMMENTED** [review]
ok

**Pull request merged**
