### PR TITLE
Add EmilienM to kubernetes, kubernetes-csi and kubernetes-client

### PR DESCRIPTION
**Pull request by EmilienM**
I'm a member of kubernetes-sigs already, this PR adds me
to kubernetes-client and kubernetes-csi.

### CODE REVIEW

**Comment by dulek** [comment]
You should update the PR title, but anyway:

/lgtm

**Comment by EmilienM** [comment]
I wonder if my old friend @dims can help to get this one :-)

**Comment by dims** [comment]
/approve
/lgtm
/ok-to-test

( don't have enough karma! but looks good :) )

**Review by mrbobbytables — COMMENTED** [review]
Sorry, KubeCon always throws a kink in the works for getting back on reviews^^;;

/approve

**Comment by EmilienM** [comment]
Thanks @mrbobbytables

**Pull request merged**
