### PR TITLE
add knelasevero to k and k-sigs

### LINKED ISSUE #3588: REQUEST: New membership for knelasevero
### GitHub Username

@knelasevero

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@damemi

### Sponsor 2

@ingvagabund

### PRs involved in (created/reviewed):
https://github.com/kubernetes-sigs/descheduler/pull/888
https://github.com/kubernetes-sigs/descheduler/pull/852
https://github.com/kubernetes-sigs/descheduler/pull/854
https://github.com/kubernetes-sigs/descheduler/pull/871
https://github.com/kubernetes-sigs/descheduler/pull/860
https://github.com/kubernetes-sigs/descheduler/pull/895
https://github.com/kubernetes-sigs/descheduler/pull/861
https://github.com/kubernetes-sigs/descheduler/pull/892
https://github.com/kubernetes/kubernetes/pull/111155

### Issues:
https://github.com/kubernetes-sigs/descheduler/issues/845
https://github.com/kubernetes/kubernetes/issues/111672
https://github.com/kubernetes/kubernetes/issues/91633
https://github.com/kubernetes-sigs/descheduler/issues/884
https://github.com/kubernetes-sigs/descheduler/issues/844
https://github.com/kubernetes-sigs/descheduler/issues/837

### SIGs I am involved with:
sig-scheduling

CC: @damemi @ingvagabund

### PR DESCRIPTION
**Pull request by knelasevero**
Closes #3588

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test

**Comment by Sea-n** [comment]
Hey @knelasevero,

In most cases, we process those membership applications by batch.

Maybe it's better to close this PR and wait for a few weeks if there is no particular reason, how do you think?

**Comment by knelasevero** [comment]
:cry:  Hi @Sea-n , sorry for bypassing that. 

Saw some other direct PRs to the org repo, and thought this would also be an option.

You mentioned 

>  wait for a few weeks if there is no particular reason

But SLOs seem to be 1 week, right? (source: https://github.com/kubernetes/community/blob/master/github-management/org-owners-guide.md#slos)

**Comment by palnabarun** [comment]
> But SLOs seem to be 1 week, right? 

Yes, it's 7days from the time when all +1's are obtained.

**Comment by palnabarun** [comment]
https://github.com/kubernetes/org/pull/3606 supersedes this.

This could have been merged as well, but #3606 adds the member with the correct commit message format.

**Comment by Sea-n** [comment]
Congrats for become a Kubernetes member! 🎉

Close as the other PR merged. 😊
/close

**Comment by knelasevero** [comment]
Thanks all!

**Pull request closed without merging**
