### PR TITLE
Add t-inu to sig-docs-ja-reviews

### PR DESCRIPTION
**Pull request by t-inu**
Add t-inu to sig-docs-ja-reviews.
ref: https://github.com/kubernetes/website/pull/35970

### CODE REVIEW

**Comment by sftim** [comment]
I'll wait for the docs JA localization team to comment.

**Comment by Sea-n** [comment]
Looks good to me since ja-owner @nasa9084 has approved.
/lgtm

**Comment by tengqm** [comment]
/approve
Reapplying from sig-docs.

**Comment by t-inu** [comment]
Thanks everyone😀

**Pull request merged**
