### PR TITLE
Add members 2019-12-03

### LINKED ISSUE #1445: REQUEST: New membership for njuettner
### GitHub Username
njuettner

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dims 
- @thockin 

### List of contributions to the Kubernetes project
- https://github.com/kubernetes-sigs/external-dns/pulls?utf8=%E2%9C%93&q=is%3Apr+njuettner+reviewed-by%3Anjuettner+
- Maintainer of https://github.com/kubernetes-sigs/external-dns

### Additional information
Follow-up https://github.com/kubernetes/k8s.io/pull/479

### LINKED ISSUE #1446: REQUEST: New membership for Raffo
### GitHub Username
@Raffo

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@thockin 
@dims 

### List of contributions to the Kubernetes project
https://github.com/kubernetes-sigs/external-dns/pulls?utf8=%E2%9C%93&q=is%3Apr+raffo+reviewed-by%3Araffo+
Maintainer of https://github.com/kubernetes-sigs/external-dns

### Additional information
Follow-up kubernetes/k8s.io#479

Similar to https://github.com/kubernetes/org/issues/1445 .

### LINKED ISSUE #1450: REQUEST: New membership for haiyanmeng
### GitHub Username
@haiyanmeng

### Organization you are requesting membership in
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @monopole
- @mrbobbytables

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  https://github.com/kubernetes-sigs/kustomize/pull/1845
  https://github.com/kubernetes-sigs/kustomize/pull/1820
  https://github.com/kubernetes-sigs/kustomize/pull/1814
  https://github.com/kubernetes-sigs/kustomize/pull/1800
  https://github.com/kubernetes-sigs/kustomize/pull/1793
  https://github.com/kubernetes-sigs/controller-tools/pull/267
  https://github.com/kubernetes-sigs/controller-tools/pull/265
  https://github.com/kubernetes-sigs/controller-tools/pull/260
  https://github.com/kubernetes-sigs/controller-tools/pull/253
  https://github.com/kubernetes-sigs/controller-tools/pull/252
  https://github.com/kubernetes-sigs/controller-tools/pull/241
  https://github.com/kubernetes-sigs/controller-tools/pull/235
  https://github.com/kubernetes-sigs/controller-tools/pull/234
- Issues responded to
  https://github.com/kubernetes-sigs/kustomize/issues/1747
  https://github.com/kubernetes-sigs/controller-tools/issues/251
  https://github.com/kubernetes-sigs/controller-tools/issues/239
  https://github.com/kubernetes-sigs/controller-tools/issues/236
  https://github.com/kubernetes-sigs/controller-tools/issues/225
- SIG projects I am involved with
  https://github.com/kubernetes-sigs/kustomize
  https://github.com/kubernetes-sigs/controller-tools

### LINKED ISSUE #1451: REQUEST: New membership for marosset
### GitHub Username
@marosset

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PatrickLang
- @michmike

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/kubernetes/pull/84882
  - https://github.com/kubernetes/test-infra/pull/15173
  - https://github.com/kubernetes-sigs/windows-testing/pull/113
- Issues responded to
- SIG projects I am involved with
  - Maintaining test configs/jobs for SIG Windows
  - Maintaining test configs/jobs for cluster-provider-azure
  - Misc SIG Windows work
  - Cluster API provider for Azure work

### LINKED ISSUE #1452: REQUEST: New membership for @joncwong
### GitHub Username
@joncwong

### Organization you are requesting membership in
@kubernetes
@kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @pwittrock
- @mrbobbytables

### List of contributions to the Kubernetes project
- PRs reviewed / authored
    - [kubernetes-sigs/kustomize#1822](https://github.com/kubernetes-sigs/kustomize/pull/1822)
- Issues responded to
    - [kubernetes-sigs/kustomize#1851](https://github.com/kubernetes-sigs/kustomize/issues/1851)
- SIG projects I am involved with
    - kubectl
    - kustomize

### PR DESCRIPTION
**Pull request by nzoueidi**
Fixes #1445
Fixes #1446
Fixes #1450
Fixes #1451
Fixes #1452

/area github-membership

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@nzoueidi please sign the CLA and squash commits :)

**Comment by nzoueidi** [comment]
Oups, I think by mistake I removed the CLA :')
/check-cla 
@idvoretskyi we don't squash commits related to the org membership requests, so we can keep track.

**Pull request merged**
