### PR TITLE
Add Members 2022-08-18

### LINKED ISSUE #3595: REQUEST: New membership for bconfiden2
### GitHub Username

bconfiden2

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@yoonian 

### Sponsor 2

@jihoon-seo 

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+commenter%3Abconfiden2
- Issues responded to
https://github.com/kubernetes/website/issues/bconfiden2
- SIG projects I am involved with
kubernetes/sig-docs

### LINKED ISSUE #3599: REQUEST: New membership for jinnypark9393
### GitHub Username

jinnypark9393

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@seokho-son

### Sponsor 2

@yoonian

### List of contributions to the Kubernetes project

- PRs reviewed / authored
https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Ajinnypark9393+
- Issues responded to
https://github.com/kubernetes/website/issues?q=is%3Aissue+author%3Ajinnypark9393
- SIG projects I am involved with
kubernetes/sig-docs

### LINKED ISSUE #3609: REQUEST: New membership for mukhoakash
### GitHub Username

@mukhoakash

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@edreed

### Sponsor 2

@wlan0

### List of contributions to the Kubernetes project

- PRs reviewed/authored
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/58
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/pull/60
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/59
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/55
https://github.com/kubernetes-sigs/container-object-storage-interface-api/pull/57
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/pull/38
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/64
- Issues responded to
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/issues/62
https://github.com/kubernetes-sigs/container-object-storage-interface-controller/issues/56
https://github.com/kubernetes-sigs/container-object-storage-interface-spec/issues/37
https://github.com/kubernetes-sigs/container-object-storage-interface-api/issues/52
- SIG projects I am involved with
kubernetes-sigs/container-object-storage-interface-controller
kubernetes-sigs/container-object-storage-interface-api
kubernetes-sigs/container-object-storage-interface-spec
kubernetes-sigs/container-object-storage-interface-provisioner-sidecar

### LINKED ISSUE #3610: REQUEST: New membership for yanrongshi
### GitHub Username

yanrongshi

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Sea-n 

### Sponsor 2

@windsonsea 

### List of contributions to the Kubernetes project

PRs authored: https://github.com/kubernetes/website/pull/35804, https://github.com/kubernetes/website/pull/35703, https://github.com/kubernetes/website/pull/35674, https://github.com/kubernetes/website/pull/35607, https://github.com/kubernetes/website/pull/35671 ,
https://github.com/kubernetes/website/pull/35606, https://github.com/kubernetes/website/pull/35682
SIG projects I am involved with: [kubernetes/website](https://kubernetes.io/docs/home/)

### LINKED ISSUE #3615: REQUEST: New membership for qbarrand
### GitHub Username

@qbarrand

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@mrunalp

### Sponsor 2

@endocrimes

### List of contributions to the Kubernetes project

- Core contributor for [Kernel Module Management](https://github.com/kubernetes-sigs/kernel-module-management), which we are moving into SIG Node (from https://github.com/qbarrand/oot-operator)
- Regular participant in SIG Node weekly meetings

### LINKED ISSUE #3616: REQUEST: New membership for wangchen615
### GitHub Username

wangchen615

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

mrunalp

### Sponsor 2

Huang-Wei

### List of contributions to the Kubernetes project

- PRs reviewed/authored
  - https://github.com/kubernetes/autoscaler/pull/4131
  - https://github.com/kubernetes/autoscaler/pull/3914
  - https://github.com/kubernetes/kubernetes/pull/102884
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/341
  - https://github.com/kubernetes-sigs/scheduler-plugins/pull/152
- Issues responded to
  - https://github.com/kubernetes-sigs/scheduler-plugins/issues/271
  - https://github.com/kubernetes-sigs/scheduler-plugins/issues/144
  - https://github.com/kubernetes/autoscaler/issues/5046
  - https://github.com/kubernetes/autoscaler/issues/3913
- SIG projects I am involved with
  - https://github.com/kubernetes/autoscaler
  - https://github.com/kubernetes-sigs/scheduler-plugins

### LINKED ISSUE #3617: REQUEST: New membership for Rishit-dagli
### GitHub Username

Rishit-dagli

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jihoon-seo

### Sponsor 2

@mehabhalodiya

### Sponsor 3

@tengqm

#### Reviews or Comments which might have been helpful

* [https://github.com/kubernetes/website/pull/35079#discussion_r924053467](https://github.com/kubernetes/website/pull/35079#discussion_r924053467)
* [https://github.com/kubernetes/website/pull/34465#discussion_r906688935](https://github.com/kubernetes/website/pull/34465#discussion_r906688935)
* [https://github.com/kubernetes/website/issues/34428#issuecomment-1163003762](https://github.com/kubernetes/website/issues/34428#issuecomment-1163003762)
* [https://kubernetes.slack.com/archives/CJDHVD54J/p1655982379049779?thread_ts=1655412831.893609&cid=CJDHVD54J](https://kubernetes.slack.com/archives/CJDHVD54J/p1655982379049779?thread_ts=1655412831.893609&cid=CJDHVD54J)

#### PRs

* [https://github.com/kubernetes-client/python/pull/1860](https://github.com/kubernetes-client/python/pull/1860)
* [https://github.com/kubernetes-client/python/pull/1812](https://github.com/kubernetes-client/python/pull/1812)
* [https://github.com/kubernetes-client/python/pull/1829](https://github.com/kubernetes-client/python/pull/1829)
* [https://github.com/kubernetes/website/pull/35763](https://github.com/kubernetes/website/pull/35763)
* [https://github.com/kubernetes/website/pull/35745](https://github.com/kubernetes/website/pull/35745)
* [https://github.com/kubernetes/website/pull/35391](https://github.com/kubernetes/website/pull/35391)
* [https://github.com/kubernetes/website/pull/35298](https://github.com/kubernetes/website/pull/35298)
* [https://github.com/kubernetes/website/pull/34425](https://github.com/kubernetes/website/pull/34425)
* [https://github.com/kubernetes/website/pull/34399](https://github.com/kubernetes/website/pull/34399)
* [https://github.com/kubernetes/website/pull/34260](https://github.com/kubernetes/website/pull/34260)
* [https://github.com/kubernetes/website/pull/35119](https://github.com/kubernetes/website/pull/35119)
* [https://github.com/kubernetes/website/pull/34499](https://github.com/kubernetes/website/pull/34499)
* [https://github.com/kubernetes/website/pull/34439](https://github.com/kubernetes/website/pull/34439)
* [https://github.com/kubernetes/website/pull/34397](https://github.com/kubernetes/website/pull/34397)
* [https://github.com/kubernetes/website/pull/34387](https://github.com/kubernetes/website/pull/34387)
* [https://github.com/kubernetes/website/pull/34386](https://github.com/kubernetes/website/pull/34386)
* [https://github.com/kubernetes/website/pull/34262](https://github.com/kubernetes/website/pull/34262)
* [https://github.com/kubernetes/website/pull/34081](https://github.com/kubernetes/website/pull/34081)
* [https://github.com/kubernetes/community/pull/6679](https://github.com/kubernetes/community/pull/6679)

#### Issues

* [https://github.com/kubernetes/website/issues/35332](https://github.com/kubernetes/website/issues/35332)
* [https://github.com/kubernetes/website/issues/34355](https://github.com/kubernetes/website/issues/34355)

### LINKED ISSUE #3619: REQUEST: New membership for hlipsig
### GitHub Username

hlipsig

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

jeremyrickard

### Sponsor 2

palnabarun

### List of contributions to the Kubernetes project

Code of Conduct Committee

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #3595
fixes #3599 
fixes #3609 
fixes #3610 
fixes #3615 
fixes #3616 
fixes #3617
fixes #3619

/area github-membership
/hold for a few more requests

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm
/approve

Thanks, Nabarun!

**Comment by savitharaghunathan** [comment]
@palnabarun I see there is a hold for pending requests. is https://github.com/kubernetes/org/issues/3617 a part of pending request?

**Comment by palnabarun** [comment]
@savitharaghunathan -- I was waiting for the remaining +1 on #3619. We are good to remove the hold now.

/hold cancel

**Comment by palnabarun** [comment]
Oops. The PR merged before the last force push.

**Comment by palnabarun** [comment]
I am raising another PR to fix the error.

**Comment by savitharaghunathan** [comment]
@palnabarun I was just going to reach out to you about that :D

**Pull request merged**
