### PR TITLE
Update external-dns admins and maintainers

### PR DESCRIPTION
**Pull request by Raffo**
This PR updates `config/kubernetes-sigs/sig-network/teams.yaml` to add a new admin and maintainer and remove an inactive one. 

/cc @szuecs

### CODE REVIEW

**Comment by Raffo** [comment]
@dcbw any chance we can get this reviewed/approved? Thanks in advance!

**Comment by Raffo** [comment]
@dcbw adding a gentle additional nudge on this one. Thanks!

**Review by MikeZappa87 — APPROVED** [review]

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
