### PR TITLE
add aojea to the milestone maintainer group

### PR DESCRIPTION
**Pull request by aojea**
I'd like to be added to the milestone maintainer group, as a person that is working in EU timezone I think that this will improve the round trip and spread the load

/assign @BenTheElder @thockin 

assign to Tim and Ben as respective Sig network and testing leads

### CODE REVIEW

**Comment by aojea** [comment]
/cc @dims @wojtek-t @liggitt @neolit123 

requesting feedback from some top approvers too

**Comment by aojea** [comment]
and from sig release friends too
@cpanato @puerco @saschagrunert @justaugustus

**Review by cpanato — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
LGTM

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
