### PR TITLE
Add juandiegopalomino to website-milestone-maintainers

### PR DESCRIPTION
**Pull request by juandiegopalomino**
cc: @zacharysarah

### CODE REVIEW

**Comment by zacharysarah** [comment]
@juandiegopalomino You’ll need to join the org first. I’m happy to sponsor you—you’ll need one more reviewer or approver, maybe ask in #sig-docs?

**Comment by nikhita** [comment]
> You’ll need to join the org first.

@juandiegopalomino  Btw for this you'll need to create an [issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) on this repo. The auto-populated issue body has more details. :)

**Comment by juandiegopalomino** [comment]
@zacharysarah ok, will do!
@nikhita sounds good, I'll open an issue as soon as I find my second sponsor!

**Comment by juandiegopalomino** [comment]
@zacharysarah @nikhita hi guys! So I joined the org, so what should me next steps be?

**Pull request merged**
