### PR TITLE
Enforce non-admins shouldn't be team maintainers

### PR DESCRIPTION
**Pull request by cblecker**
This is a manual revert of https://github.com/kubernetes/org/pull/591, and a retake of https://github.com/kubernetes/org/pull/592

If this looks good, I'll do a manual peribolos run to fix any weird errors that arise.

### CODE REVIEW

**Comment by cblecker** [comment]
/hold cancel

Let’s let the auto run go, and I’ll inspect the results.

**Comment by nikhita** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-org-peribolos/1133752154507448320 :disappointed:

**Comment by rlenferink** [comment]
It looks like peribolos is returning the same error message as described in #591

**Comment by cblecker** [comment]
I ran it locally with my token, and didn't encounter errors. Very curious.

**Comment by nikhita** [comment]
> I ran it locally with my token, and didn't encounter errors. 

Now that the actual teams reflect the config with this run, hopefully we don't see any errors in the ci... :crossed_fingers:

**Comment by cblecker** [comment]
Yeah, that's my hope too. Still unsure what the error was. The bot looks like it has the right permissions and such. I'm asking test-infra to re-run the CI job.

**Comment by nikhita** [comment]
> I'm asking test-infra to re-run the CI job.

The latest CI run was green! :tada: 

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-org-peribolos/1133790031064862720

**Pull request merged**
