### PR TITLE
Update for teams.yaml for Bug Triage 1.21

### PR DESCRIPTION
**Pull request by erismaster**
Adding new bug triage team members and cleaning up old team members from
1.20.

Resolves #2423, #2425.

### CODE REVIEW

**Comment by erismaster** [comment]
cc @palnabarun 

/assign @alejandrox1

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

/hold for reviews 
cc: @palnabarun

**Comment by savitharaghunathan** [comment]
@erismaster 👋 Thanks for the PR. Looks like there is a merge conflict, can you resolve it when you get a moment?

**Comment by erismaster** [comment]
@savitharaghunathan Rebased and resolved the conflict. Thanks!

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
Thank you @erismaster 👍🏽 

/lgtm
/approve

/hold cancel

**Pull request merged**
