### PR TITLE
Add annajung to website-maintainers team for 1.20 release

### PR DESCRIPTION
**Pull request by annajung**
Temporary adding myself to the `website-maintainers` team for write access to k/website repo for the release preparation/release day.

/assign @jimangel @irvifa @kbarnard10

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by irvifa** [comment]
When you create a PR for the release handbook would you please link this PR to that PR as well?

**Comment by annajung** [comment]
>When you create a PR for the release handbook would you please link this PR to that PR as well?

Already done! https://github.com/kubernetes/sig-release/pull/1354

**Comment by annajung** [comment]
/hold cancel
it's a day before the release. Write access will allow me to freeze the repo and complete all the necessary task to prepare for the release day / for the release day.

**Comment by kbhawkey** [comment]
Ping @irvifa  for approval

**Pull request merged**
