### PR TITLE
Add chrigl and jichenjc into cluster-api-openstack maintainer

### PR DESCRIPTION
**Pull request by jichenjc**
Request to add chrigl and jichenjc into cluster-api-openstack maintainer
as we need create branch and other admin privileges..

### CODE REVIEW

**Comment by jichenjc** [comment]
@chaosaffe @dims @chrigl

**Comment by dims** [comment]
@nikhita @cblecker - is maintainer enough for creating branches? what other extra stuff would an admin have over a maintainer?

**Comment by nikhita** [comment]
> is maintainer enough for creating branches?

Yes, maintainers have write access and they can create branches and releases.

> what other extra stuff would an admin have over a maintainer?

Admins have extremely elevated privileges compared to maintainers (even like manually merging a PR even if the tests fail!) but the main ones that are useful to us:

- If a branch is pushed to the repo accidentally (clicking on the revert option in the UI is a common culprit), admins can manually remove the branch protection setting for that branch and delete it. Otherwise, all branches are protected by default and cannot be deleted.

- Admins receive security alerts, if they are enabled.

- Admins can delete issues for moderation purposes, etc.

Ref: https://help.github.com/en/articles/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level

**Comment by jichenjc** [comment]
@dims @chaosaffe please share your opinion , thanks a lot

**Comment by dims** [comment]
@jichenjc can you please update the PR to limit to being maintainers?

**Comment by jichenjc** [comment]
ok, maintainers only now @dims

**Pull request merged**
