### PR TITLE
remove docs release 1.22 team from sig-release.

### PR DESCRIPTION
**Pull request by PI-Victor**
Signed-off-by: Victor Palade <victor@cloudflavor.io>

### CODE REVIEW

**Comment by PI-Victor** [comment]
cc @kubernetes/sig-release-leads

**Comment by PI-Victor** [comment]
@reylejano could you please approve this, by any chance?

**Comment by justaugustus** [comment]
Thanks for the cleanup, @PI-Victor!
/lgtm
/approve

**Pull request merged**
