### PR TITLE
Add team members to application-admins

### PR DESCRIPTION
**Pull request by nan-yu**

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@nan-yu This won't be able to be merged until you're a member first.

**Comment by nan-yu** [comment]
blocked by https://github.com/kubernetes/org/pull/1600. Will reopen when #1600 is ready.

**Comment by nan-yu** [comment]
reopen this as membership is done via https://github.com/kubernetes/org/pull/1652

**Comment by cblecker** [comment]
/ok-to-test
/unassign
/assign @janetkuo @mattfarina 

Is admin access to this repo needed, as opposed to just write access? What are you attempting to do?

**Comment by nan-yu** [comment]
> Is admin access to this repo needed, as opposed to just write access? What are you attempting to do?

Initially, I was planning to enable the application repo on Travis and that requires admin access. Janet helped enabling the repo, but we still need permissions like restart build without push.

**Comment by justaugustus** [comment]
What are next steps here?

**Comment by nikhita** [comment]
> What are next steps here?

Needs approval from existing admins... assigning other admins too.

/assign @kow3ns @prydonius

**Comment by prydonius** [comment]
sorry for the delay

/approve

**Pull request merged**
