### PR TITLE
Update service catalog teams

### LINKED ISSUE #844: REQUEST: clean up SIG Service Catalog teams
### Organization or repository
kubernetes-incubator, kubernetes, and kubernetes-sigs

### Users affected
all users of the `admins-service-catalog` and `maintainers-service-catalog` teams in kubernetes-incubator, as well as members of the `sig-service-catalog-api-reviews`, `sig-service-catalog-bugs`, `sig-service-catalog-feature-requests `, `sig-service-catalog-misc`, `sig-service-catalog-pr-reviews, `sig-service-catalog-proposals`, and `sig-service-catalog-test-failures` teams in kubernetes

### Describe the issue
We're beginning the process of migrating our repos out of kubernetes-incubator to kubernetes-sigs. I need the `admins-service-catalog`  and `maintainers-service-catalog` teams from kubernetes-incubator duplicated in kubernetes and kubernetes-sigs. I would like to change the names to the current naming convention, so they would be called `service-catalog-admins` and `service-catalog-maintainers`. I would also like to delete the other teams from the mainline kubernetes org, as they are deprecated and have no current function.

### PR DESCRIPTION
**Pull request by cblecker**
fixes #844.
cc: @jberkhahn

### CODE REVIEW

**Comment by jberkhahn** [comment]
Ah, looks like I need to apply for kubernetes-sig membership.

As for Jay and Kibbles, neither of them are still actively contributing to the project, so they could be removed from the lists. I'm not sure what standard procedure for that is, though.

**Comment by cblecker** [comment]
```
config_test.go:250: The following members of team service-catalog-maintainers are not Kubernetes SIGs org members: arschles, duglin, eriknelson, jberkhahn, jboyd01, jpeeler, kibbles-n-bytes, luksa, martinmaly, mhbauer, n3wscott, nilebox, slack, staebler, vaikas-google
config_test.go:250: The following members of team service-catalog-admins are not Kubernetes SIGs org members: jberkhahn, jboyd01
config_test.go:250: The following members of team sig-service-catalog are not Kubernetes org members: jboyd01, kibbles-n-bytes
```

**Pull request merged**
