### PR TITLE
Add teams for French localization

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubernetes/org/issues/532

/assign @zacharysarah

### CODE REVIEW

**Comment by nikhita** [comment]
@abuisine and @erickhun are not Kubernetes GitHub org members, so they can't be added to teams. Can you both [apply](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) for org membership though? This will help you in using your lgtm and approval powers. :)

**Comment by abuisine** [comment]
> @abuisine and @erickhun are not Kubernetes GitHub org members, so they can't be added to teams. Can you both [apply](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) for org membership though? This will help you in using your lgtm and approval powers. :)

I am now part of it \o/

**Comment by nikhita** [comment]
@abuisine Awesome! :tada: 

I've asked @rlenferink to add you to the teams in his PR: https://github.com/kubernetes/org/pull/546#discussion_r261481250 :)

**Pull request merged**
