### PR TITLE
Add Rishit-dagli to website-maintainers team for 1.28 release

### PR DESCRIPTION
**Pull request by Rishit-dagli**
Temporarily adding myself to the website-maintainers team for write access to the k/website repo for the release preparation/release day.

/assign @divya-mohan0209 @natalisucks @reylejano

(SIG Docs Chairs)

### CODE REVIEW

**Comment by reylejano** [comment]
@Rishit-dagli is the 1.28 docs lead on the 1.28 release team
Temporary write access is required for release-day tasks as stated in the release team docs handbook timeline: https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#day-before-release-day

/approve

**Review by sftim — COMMENTED** [review]
/lgtm

**Pull request merged**
