### PR TITLE
Add sig-docs-vi members

### PR DESCRIPTION
**Pull request by truongnh1992**
Owners and reviewers for the Vietnamese translation team joined at kubernetes/website#16965

Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

### CODE REVIEW

**Comment by nikhita** [comment]
@truongnh1992 You'll need to be a member of the org to be added to a team. Could you open a [membership request](https://github.com/kubernetes/community/blob/master/community-membership.md#member) first? Thanks!

**Comment by truongnh1992** [comment]
> @truongnh1992 You'll need to be a member of the org to be added to a team. Could you open a [membership request](https://github.com/kubernetes/community/blob/master/community-membership.md#member) first? Thanks!

Hi @nikhita. I would like to contribute to Kubernetes documentation in Vietnamese. Could you nominate me as a member of Kubernetes, please. I've had 5 PRs merged in Kubernetes and some PRs in other CNCF projects as well
Here's my profile on stackalytics https://www.stackalytics.com/cncf?user_id=truongnh92

Thank you.

**Comment by nikhita** [comment]
> Could you nominate me as a member of Kubernetes, please.

@truongnh1992 Sponsors generally need to be folks who've reviewed PRs from the person requesting membership. Since you'd like to contribute to localization/docs, I'd suggest reaching out to the [SIG Docs Leads](https://github.com/kubernetes/community/tree/master/sig-docs#chairs) for sponsorship.

If you still face trouble getting sponsors, feel free to ping me on slack (I am `@nikhita` there) and I can help follow-up. :)

**Comment by zacharysarah** [comment]
@truongnh1992 Thanks for your interest in localizing Vietnamese content! 

As mentioned in the [docs guide to localization](https://kubernetes.io/docs/contribute/localization/#getting-started), you need at least two people to start a localization. (This is so you can review and approve each other's PRs. More than two is helpful!) Is there someone else who can help localize content into Vietnamese?

**Comment by cblecker** [comment]
@truongnh1992 As this PR is not actionable yet (you aren't a part of the org, and there isn't yet a Vietnamese translation team), I'm going to close this specific PR out. I'd suggest contacting @zacharysarah and the docs team directly to work out those details first.

Thank you!
/close

**Comment by ngtuna** [comment]
@truongnh1992 You can count me in this team once you get approved to create it.
@nikhita Hey Nikhita, saw you around Kubeless development while ago but haven't got chance to meet in person 👋

**Comment by zacharysarah** [comment]
@ngtuna 👋🏻 To clarify: will you be joining the Vietnamese localization? Do you have native or advanced fluency in Vietnamese?

**Comment by truongnh1992** [comment]
> 
> 
> @ngtuna 👋🏻 To clarify: will you be joining the Vietnamese localization? Do you have native or advanced fluency in Vietnamese?

Hi @zacharysarah,
@ngtuna is Vietnamese :D

**Comment by ngtuna** [comment]
@zacharysarah Yes. Vietnamese is my mother tongue :-)

**Comment by zacharysarah** [comment]
@ngtuna Thanks for the quick reply. 😊

**Pull request closed without merging**
