### PR TITLE
Add members 2021-04-21

### LINKED ISSUE #2665: REQUEST: New membership for ritpanjw
### GitHub Username
@ritpanjw

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @PI-Victor 
- @savitharaghunathan 

### List of contributions to the Kubernetes project
- Selected as shadow for SIG Docs 1.22 Release Team

### LINKED ISSUE #2667: REQUEST: New membership for moonming
### GitHub Username
@moonming

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @rikatz
- @ElvinEfendi

### List of contributions to the Kubernetes project
- PRs reviewed / authored: 
    - https://github.com/kubernetes/ingress-nginx/commits?author=moonming
- SIG projects I am involved with `Ingress NGINX`

### LINKED ISSUE #2668: REQUEST: New membership Request for encodeflush
### GitHub Username
@encodeflush

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
@mkorbi
@guineveresaenger 

### List of contributions to the Kubernetes project
- Joining CI Signal shadow for Kubernetes 1.22

### LINKED ISSUE #2670: REQUEST: New membership for lambdanis
### GitHub Username
@lambdanis

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mkorbi
- @guineveresaenger

### List of contributions to the Kubernetes project
I'm a CI Signal shadow for Kubernetes 1.22

### LINKED ISSUE #2672: REQUEST: New membership for jgavinray
### GitHub Username
@jgavinray

### Organization you are requesting membership in
@kubernetes

### Requirements
- [X] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [X] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MonzElmasry
- @savitharaghunathan

### List of contributions to the Kubernetes project
I'm a bug triage shadow for Kubernetes 1.22

### LINKED ISSUE #2673: REQUEST: New membership for @Damans227
### GitHub Username
@Damans227

### Organization you are requesting membership in
e.g. (at)kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @guineveresaenger
- @pmmalinov01 

### List of contributions to the Kubernetes project

- PR merged: https://github.com/kubernetes/sig-release/pull/1542
- Release Notes Shadow for 1.22

### LINKED ISSUE #2674: REQUEST: New membership for voigt
### GitHub Username
@voigt

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MonzElmasry
- @guineveresaenger

### List of contributions to the Kubernetes project
I'm a Bug Triage shadow for Kubernetes 1.22

### LINKED ISSUE #2675: REQUEST: New membership for @notchairmk
### GitHub Username
@notchairmk

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @MonzElmasry
- @savitharaghunathan

### List of contributions to the Kubernetes project
- Joining release team as a bug triage shadow for the 1.22 release.
- PRs review/authored:
https://github.com/kubernetes/website/pull/26278
https://github.com/kubernetes/website/pull/26062
https://github.com/kubernetes/website/pull/23294
https://github.com/kubernetes/website/pull/22934

### LINKED ISSUE #2676: REQUEST: New membership for kunal-kushwaha
### GitHub Username
@kunal-kushwaha

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Pensu
- @savitharaghunathan

### List of contributions to the Kubernetes project
- PRs reviewed / authored: Sig-Usability Blog WIP
- Issues responded to: contributor-tweets, SIG Profiling Articles
- SIG projects I am involved with: Kubernetes 1.22 Release Shadow, Marketing & ContribEx

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #2665 
fixes #2668 
fixes #2670 
fixes #2672 
fixes #2673 
fixes #2674 
fixes #2675 
fixes #2676
fixes #2667

/assign @nikhita

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by palnabarun** [comment]
@nikhita -- one more LGTM please. :)

**Pull request merged**
