### PR TITLE
Add myself to k8s.io/kops

### PR DESCRIPTION
**Pull request by mikesplain**
Adding myself to kops to help Justin with some overrides, given aws e2e issues and issue triage.

cc @justinsb

### CODE REVIEW

**Comment by cblecker** [comment]
/cc @justinsb 
Please review and provide feedback

**Comment by mikesplain** [comment]
@justinsb updated as we discussed.  Thanks!

**Comment by justinsb** [comment]
/approve

Thanks @mikesplain & welcome to the party!

**Pull request merged**
