### PR TITLE
Add Members 2022-03-11

### LINKED ISSUE #3287: REQUEST: New membership for shawnhanx
### GitHub Username

@shawnhanx

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@xiangpengzhao

### Sponsor 2

@tengqm

### List of contributions to the Kubernetes project

- kubernetes/kubernetes/pull/97321
- kubernetes/kubernetes/pull/101092
- kubernetes/kubernetes/pull/104429
- kubernetes/kubernetes/pull/104807
- kubernetes/kubernetes/pull/105603
- kubernetes/kubernetes/pull/105621
- kubernetes/kubernetes/pull/106215
- kubernetes/kubernetes/pull/106397
- kubernetes/kubernetes/pull/106398
- kubernetes/kubernetes/pull/100600
- kubernetes/kubernetes/pull/101997
- kubernetes/kubernetes/pull/104353
- kubernetes/kubernetes/pull/104386
- kubernetes/kubernetes/pull/105209
- kubernetes/kubernetes/pull/105229
- kubernetes/kubernetes/pull/105570
- kubernetes/kubernetes/pull/106225
- kubernetes/kubernetes/pull/107362
- kubernetes/website/pull/31752

### LINKED ISSUE #3289: REQUEST: New membership for SanikaGawhane
### GitHub Username

@SanikaGawhane

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@codenrhoden

### Sponsor 2

@CecileRobertMichon

### List of contributions to the Kubernetes project

image-builder
https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3Asanikagawhane+

k8s.io (for image-promotions)
https://github.com/kubernetes/k8s.io/pulls?q=is%3Apr+author%3ASanikaGawhane

test-infra
https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3ASanikaGawhane

cluster-api-provider-aws
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+author%3ASanikaGawhane

### LINKED ISSUE #3290: REQUEST: New membership for shalini-b
### GitHub Username

@shalini-b

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@divyenpatel

### Sponsor 2

@RaunakShah

### List of contributions to the Kubernetes project

PRs reviewed/authored:
https://github.com/kubernetes-sigs/vsphere-csi-driver/pulls?q=is%3Apr+is%3Aclosed+author%3Ashalini-b

SIG projects I am involved with
https://github.com/kubernetes-sigs/vsphere-csi-driver

### LINKED ISSUE #3291: REQUEST: New membership for mitul3737
### GitHub Username

mitul3737

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

anubha-v-ardhan

### Sponsor 2

verma-kunal

### List of contributions to the Kubernetes project

1. PR merged:

- [en] Solved some typos "hostname of FQDN" and "PowerShell": https://github.com/kubernetes/website/pull/31865…

2. The PR's I created :

-  [bn] Updated config.toml : https://github.com/kubernetes/website/pull/31840…

-  [WIP] [bn] Localize content/bn/docs/home/_index.md: https://github.com/kubernetes/website/pull/31838…

-  [bn] http://Readme-bn.md : https://github.com/kubernetes/website/pull/31839…

-  Adding label for Bengali language: https://github.com/kubernetes/test-infra/pull/25343…

-  [bn] Localized Code of Conduct in Bengali : https://github.com/cncf/foundation/pull/305…

3. Issues Created:

-  Umbrella issue: localize Kubernetes website to Bengali: https://github.com/kubernetes/website/issues/31677…

### LINKED ISSUE #3293: REQUEST: New membership for Dyanngg
### GitHub Username

@Dyanngg

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@astoycos

### Sponsor 2

@rikatz

### List of contributions to the Kubernetes project

I have worked on the AdminNetworkPolicy resource KEP (https://github.com/kubernetes/enhancements/pull/2522) since inception. I have also been an active participant of sig-network and sig-network-api meetings. In addition, I'm now working on adding new commits to the new [network-policy-api repo](https://github.com/kubernetes-sigs/network-policy-api), which will house new CRDs related to K8s Security.

### LINKED ISSUE #3294: REQUEST: New membership for phillipsj
### GitHub Username

@phillipsj

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@marosset

### Sponsor 2

@jayunit100

### List of contributions to the Kubernetes project

PRs:
* https://github.com/kubernetes-sigs/windows-gmsa/pull/57
* https://github.com/kubernetes-sigs/windows-gmsa/pull/55
* https://github.com/kubernetes/k8s.io/pull/3161
* https://github.com/kubernetes/klog/pull/271

Issues:
* https://github.com/kubernetes-sigs/windows-gmsa/issues/40
* https://github.com/kubernetes-sigs/windows-gmsa/issues/52

Subprojects Contributions/Participation:
* https://github.com/kubernetes-sigs/windows-gmsa
* https://github.com/kubernetes-sigs/sig-windows-dev-tools

### LINKED ISSUE #3301: REQUEST: New membership for marckhouzam
### GitHub Username

@marckhouzam

### Organization you are requesting membership in

kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@eddiezane

### Sponsor 2

@brianpursley

### List of contributions to the Kubernetes project

Merged PRs:
https://github.com/kubernetes/kubernetes/pull/105711
https://github.com/kubernetes/kubernetes/pull/105851
https://github.com/kubernetes/kubernetes/pull/105141
https://github.com/kubernetes/kubernetes/pull/96087

Open PRs:
https://github.com/kubernetes/kubernetes/pull/108493
https://github.com/kubernetes/kubernetes/pull/105867

Issues I responded to:
https://github.com/kubernetes/kubernetes/issues/59078
https://github.com/kubernetes/kubernetes/issues/74178
https://github.com/kubernetes/kubernetes/issues/94927
https://github.com/kubernetes/kubernetes/issues/105587
https://github.com/kubernetes/kubectl/issues/576
https://github.com/kubernetes/kubectl/issues/613
https://github.com/kubernetes/kubectl/issues/882
https://github.com/kubernetes/kubectl/issues/890
https://github.com/kubernetes/kubectl/issues/1116
https://github.com/kubernetes/kubectl/issues/1119
https://github.com/kubernetes/kubectl/issues/1135
https://github.com/kubernetes/kubectl/issues/1139
https://github.com/kubernetes/kubectl/issues/1157
https://github.com/kubernetes/kubectl/issues/1180
https://github.com/kubernetes/kubectl/issues/1181

### LINKED ISSUE #3303: REQUEST: New membership for @bigdarkclown
### GitHub Username

@bigdarkclown

### Organization you are requesting membership in

@kubernetes

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)

### Sponsor 1

@maciekpytel

### Sponsor 2

@gjtempleton

### List of contributions to the Kubernetes project

- PRs authored
https://github.com/kubernetes/autoscaler/pulls?q=is%3Apr+is%3Aclosed+author%3Abigdarkclown

- SIG projects I am involved with
Autoscaler (Cluster Autoscaler)

### LINKED ISSUE #3304: REQUEST: New membership for Abirdcfly
### GitHub Username

@Abirdcfly

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Huang-Wei

### Sponsor 2

@damemi

### List of contributions to the Kubernetes project

Merged PRs:
- https://github.com/kubernetes/kubernetes/pull/108535
- https://github.com/kubernetes/kubernetes/pull/108479
- https://github.com/kubernetes/kubernetes/pull/108473
- https://github.com/kubernetes/kubernetes/pull/108239
- https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/211
- https://github.com/kubernetes/website/pull/29468
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/72
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/71
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/70
- https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/69
- https://github.com/kubernetes-sigs/kubefed/pull/1279

Open PRs:
- https://github.com/kubernetes/website/pull/32116
- https://github.com/kubernetes/kubernetes/pull/108484

### LINKED ISSUE #3306: REQUEST: New membership for JaneLiuL
### GitHub Username

JaneLiuL

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@damemi

### Sponsor 2

@ingvagabund

### List of contributions to the Kubernetes project

Sig Projects: https://github.com/kubernetes-sigs/descheduler
PR: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+is%3Aclosed+janeliul
Issues: https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+janeliul

### LINKED ISSUE #3307: REQUEST: New membership for chrismetz09
### GitHub Username

@chrismetz09

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Rey Lejano

### Sponsor 2

@jimangel

### List of contributions to the Kubernetes project

[Authored PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Achrismetz09+is%3Aclosed)

[Kubecon 2021 Kubernetes SIG Docs: Deep-Dive, co-author/co-presenter](https://www.youtube.com/watch?v=GDfcBF5et3Q)

[Kubernetes contributor blog, "Improve your documentation with Mermaid.js diagrams" co-author with Tim Bannister](https://www.kubernetes.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/)

### LINKED ISSUE #3308: REQUEST: New membership for josh-ferrell
### GitHub Username

josh-ferrell

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sedefsavas

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

- kubernetes-sigs/cluster-api-provider-aws#3133
- kubernetes-sigs/cluster-api-provider-aws#3237
- kubernetes-sigs/cluster-api-provider-aws#3251
- kubernetes-sigs/cluster-api-provider-aws#3285
- kubernetes-sigs/cluster-api-provider-aws#3291
- kubernetes-sigs/cluster-api#6277

### LINKED ISSUE #3309: REQUEST: New membership for apricote
### GitHub Username

@apricote

### Organization you are requesting membership in

kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@sbueringer

### Sponsor 2

@tobiasgiese

### List of contributions to the Kubernetes project

- PRs authored
  - [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
  - [kubernetes-sigs/cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
  - [kubernetes-sigs/image-builder](https://github.com/kubernetes-sigs/image-builder/pulls?q=is%3Apr+author%3Aapricote+is%3Aclosed)
- Issues opened
  - [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aissue+author%3Aapricote)

### LINKED ISSUE #3310: REQUEST: New membership for meghanajangi
### GitHub Username

meghanajangi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@Ankitasw

### Sponsor 2

@richardcase

### List of contributions to the Kubernetes project

**PRs reviewed / authored**
- https://github.com/kubernetes-sigs/cluster-api/pull/6114 
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3222
- https://github.com/kubernetes/test-infra/pull/25294
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3278
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3214

**Issues responded to**
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2152
- https://github.com/kubernetes-sigs/cluster-api/issues/6267
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2127

**SIG projects I am involved with**

- cluster-api
- cluster-api-provider-azure
- cluster-api-provider-aws

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #3287
fixes #3289 
fixes #3290 
fixes #3291 
fixes #3293 
fixes #3294 
fixes #3301 
fixes #3303 
fixes #3304 
fixes #3306 
fixes #3307  
fixes #3308 
fixes #3309 
fixes #3310

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

### CODE REVIEW

**Comment by Dyanngg** [comment]
Hi @palnabarun @nikhita somehow I missed the invitation email and it is now expired. Would you be able to re-send another invite? Apologize in advance for the inconvience.

**Comment by nikhita** [comment]
@Dyanngg resent the invite :+1:

**Comment by Dyanngg** [comment]
> @Dyanngg resent the invite 👍

Thanks!

**Pull request merged**
