### PR TITLE
Update Milestone Members | Add CIPHERTron

### PR DESCRIPTION
**Pull request by CIPHERTron**
Hello, this is Pritish Samal, an undergrad from India & I wanted to apply for the Documentation role for the K8s Release Team Shadow and in order to apply for that role, the prerequisite is that he/she has to be a `milestone-member`. Hence, this PR is a form of a request to accept me as a `milestone-member`. I'm willing to dedicate the required amount of time per week tracking documentation PRs, monitoring slack & attending SIG Docs meetings for status reports.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/ok-to-test

I think Prow will have some feedback on this though.

**Comment by CIPHERTron** [comment]
> /ok-to-test
> 
> I think Prow will have some feedback on this though.

@sftim could you please guide me on what to do now?
The check is failing because I'm not a member of the Kubernetes org which is true 😅

**Comment by cblecker** [comment]
@CIPHERTron Being added to this group is not a pre-requisite. If you have questions about applying to the release team, I'd reach out in the #sig-release channel in slack.

/close

**Pull request closed without merging**
