### PR TITLE
Added self as maintainer for aws-ebs-csi-driver

### PR DESCRIPTION
**Pull request by nirmalaagash**
Added self as maintainer for aws-ebs-csi-driver. Needed for the release process.

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
/cc @wongma7
looking for lgtm from another member of the team if approvers requested here are unresponsive

**Comment by wongma7** [comment]
/lgtm 
@nirmalaagash you have to join the kubernetes-sigs org first before the test will pass, see https://github.com/kubernetes/community/blob/master/community-membership.md for how to open an issue. Note the docs says it's WIP and seems written for kubernetes org not kubernetes-sigs so let's just open an issue and go from there.

**Pull request closed without merging**
