### PR TITLE
Add sig-docs-ru members

### PR DESCRIPTION
**Pull request by Potapy4**
Add owners and reviewers for RU transaltion team.

Related to kubernetes/website#16404

### CODE REVIEW

**Comment by zacharysarah** [comment]
@Potapy4 Thanks for making these updates. Please wait for #1375 to merge, then add folks to `website-maintainers` instead of `sig-docs-l10n-admins`. Otherwise LGTM

/approve
/hold
/assign @jimangel @Bradamant3

**Comment by Potapy4** [comment]
> @Potapy4 Thanks for making these updates. Please wait for #1375 to merge, then add folks to `website-maintainers` instead of `sig-docs-l10n-admins`. Otherwise LGTM
> 
> /approve
> /hold
> /assign @jimangel @Bradamant3

Ready 🙂

**Comment by sftim** [comment]
Not sure when it's OK to unhold this one.

**Pull request merged**
