### PR TITLE
Add self to kompose-admins, kompose-maintainers

### PR DESCRIPTION
**Pull request by AhmedGrati**
Add myself `AhmedGrati` to `kompose-admin` and `kompose-maintainers`.

### CODE REVIEW

**Comment by ameukam** [comment]
@AhmedGrati can we get a LGTM for the SIG Apps chairs before approval ?

**Comment by cdrage** [comment]
> Member

Whoops, forgot to LGTM / approve this.

Myself, @AhmedGrati and @hangyan are the only maintainers / contributors to Kompose now, everyone else hasn't contributed for years.

This LGTM

/lgtm

**Comment by cdrage** [comment]
ping @ameukam

**Pull request merged**
