### PR TITLE
Add members 2020-07-24

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubernetes/org/issues/2058
Fixes https://github.com/kubernetes/org/issues/2059

/assign @mrbobbytables

### CODE REVIEW

**Comment by fisherxu** [comment]
@nikhita @mrbobbytables Small question... Now if the PR get merged, the bot will send the membership invitation automatically?

**Comment by nikhita** [comment]
@fisherxu yes :)

**Comment by fisherxu** [comment]
> @fisherxu yes :)

Get it, coool!

**Pull request merged**
