### PR TITLE
Add dims as maintainer for k/k8s.io repo

### PR DESCRIPTION
**Pull request by dims**
cc @lavalamp @rmmh @thockin @ixdy

### CODE REVIEW

**Comment by nikhita** [comment]
This is a legit test failure.

```
--- FAIL: TestAllOrgs (0.08s)
    config_test.go:248: The team k8s.io-maintainers in org Kubernetes has an unsorted list of members
```

**Comment by dims** [comment]
fixed. thanks @nikhita

**Comment by dims** [comment]
/hold cancel

thanks!

**Pull request merged**
