### PR TITLE
Grant approval privileges to NMCs for active orgs

### PR DESCRIPTION
**Pull request by nikhita**
Implements https://github.com/kubernetes/community/pull/4463

/hold
until https://github.com/kubernetes/community/pull/4463 and https://github.com/kubernetes/community/pull/4462 merge

/cc @kubernetes/owners @justaugustus @nzoueidi @idealhack

### CODE REVIEW

**Comment by cblecker** [comment]
@nikhita Is there a reason we removed them as reviewers? I'd like NMCs to be front line for new PRs

**Comment by nikhita** [comment]
@cblecker Good point, fixed :+1:

**Comment by nikhita** [comment]
/hold cancel

Both PRs have merged :rocket:

**Pull request merged**
