### PR TITLE
sig-instrumentation: Prune team

### PR DESCRIPTION
**Pull request by brancz**
@kubernetes/sig-instrumentation-misc

### CODE REVIEW

**Comment by justaugustus** [comment]
From k/org:
/lgtm
/approve

Lift the hold if everything looks good.

**Comment by RainbowMango** [comment]
I can't access the test log. Retry once.
/test pull-org-test-all

**Comment by nikhita** [comment]
```
 --- FAIL: TestAllOrgs (0.05s)
    config_test.go:246: The following members of team sig-instrumentation-feature-requests are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-feature-requests in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-pr-reviews are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-pr-reviews in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-api-reviews are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-api-reviews in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-bugs are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-bugs in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-test-failures are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-test-failures in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-misc are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-misc in org Kubernetes has an unsorted list of members
    config_test.go:246: The following members of team sig-instrumentation-proposals are not Kubernetes org members: 44past4
    config_test.go:246: The team sig-instrumentation-proposals in org Kubernetes has an unsorted list of members 
```

**Comment by nikhita** [comment]
@44past4 would need to apply for org membership in order to be added to a team.

**Comment by brancz** [comment]
Ah I see, I was totally under the assumption that he already was :smile: . Then I'll remove this from this PR for now and then add him as soon as he's part of the org.

**Comment by nikhita** [comment]
/lgtm

Feel free to cancel the hold at your discretion :)

**Comment by RainbowMango** [comment]
/hold cancel
Thanks, @nikhita .

**Comment by piosz** [comment]
I suggest re-adding loburm back as he's been on leave for some period of time recently.

**Comment by 44past4** [comment]
I have created an issue (https://github.com/kubernetes/org/issues/1672) to apply for org membership.

**Pull request merged**
