### PR TITLE
Add marosset and remove patricklang as milestone maintainers for sig windows

### PR DESCRIPTION
**Pull request by marosset**

### CODE REVIEW

**Comment by tpepper** [comment]
Given https://github.com/kubernetes/community/pull/4575, makes sense.  Before lgtm/approve, I want to check is Patrick continuing on enough to stay or should the commit on k/org similar to k/community swizzle Patrick for Mark?

**Comment by marosset** [comment]
Might make more sense to swizzle - I don't think Patrick will be very involved in the near term.
Let me update the PR.

**Comment by justaugustus** [comment]
Thanks @marosset and congrats!
/lgtm
/approve

**Comment by marosset** [comment]
Thanks!

**Pull request merged**
