### PR TITLE
CAPI: Add adilGhaffarDev to the release team after membership was obtained

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
I am uncommenting myself in the capi release team because now I am a member Kubernetes-sigs

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
@furkatgofurov7

**Comment by furkatgofurov7** [comment]
/retitle CAPI: Add adilGhaffarDev to the release team after membership was obtained

Membership request: https://github.com/kubernetes/org/issues/4582
Thanks @adilGhaffarDev, welcome!

/lgtm
/cc @vincepri @CecileRobertMichon

**Comment by adilGhaffarDev** [comment]
closing because this change is being done in https://github.com/kubernetes/org/pull/4619

**Pull request closed without merging**
