### PR TITLE
Add GitHub teams for maintainers

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/org/issues/3208

/assign @palnabarun

### CODE REVIEW

**Comment by dims** [comment]
hmm ... broken test

--- FAIL: TestAllOrgs (0.02s)
    config_test.go:2[72](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/org/3300/pull-org-test-all/1499226770962911232#1:build-log.txt%3A72): The team maintainers-maintainers in org Kubernetes SIGs has org admins listed as members; these users should be in the maintainers list instead, and cannot be on the members list: mrbobbytables

**Review by cblecker — APPROVED** [review]

**Pull request merged**
