### PR TITLE
Add irvifa as lead as a preparation step for transition

### PR DESCRIPTION
**Pull request by irvifa**
As mentioned in previous meeting, there's various step needed to be taken care of as a preparation for the shadow role for chairs.

### CODE REVIEW

**Comment by zacharysarah** [comment]
/hold for explicit review and approval by SIG Docs chairs

@irvifa We will need to do this several months from now, but there are some preliminary steps. For now, please add yourself alphabetically to the following blocks instead:
- https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L16
- https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L38
- https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L353

**Comment by irvifa** [comment]
@zacharysarah I've created a PR for this: https://github.com/kubernetes/org/pull/1972

**Comment by cblecker** [comment]
@irvifa @zacharysarah @jimangel @kbhawkey As #1972 merged, should this PR now be closed for the time being?

**Comment by zacharysarah** [comment]
@cblecker Good call—closing for now.

/close

**Pull request closed without merging**
