### PR TITLE
kubernetes-sigs: Add mrueg as member

### PR DESCRIPTION
**Pull request by mrueg**
As requested by @ehashman in https://github.com/kubernetes-sigs/usage-metrics-collector/pull/25#issuecomment-1405394309

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by mrueg** [comment]
@mrbobbytables @nikhita anything that I can do to move this forward?

**Comment by ehashman** [comment]
Maybe try pinging someone in #github-admins on Slack? This probably just got lost.

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
