### PR TITLE
Adding more owners to external-dns

### PR DESCRIPTION
**Pull request by njuettner**
After joining the kubernetes-sigs I'd request admin access for the other owners:

- @Raffo
- @hjacobs
- @njuettner

/cc @nikhita 
/cc @mrbobbytables 

Signed-off-by: njuettner <nick@zalando.de>

### CODE REVIEW

**Comment by Raffo** [comment]
Testing YAMLs is always special 😄

**Comment by mrbobbytables** [comment]
@njuettner would you mind squashing your commits? 😬 we try and keep this repo's history as clean as possible since it is our org source of truth.

**Comment by njuettner** [comment]
@mrbobbytables totally understandable 🙂, I squashed them. Thanks again!

**Pull request merged**
