### PR TITLE
Add umohnani8 to cri-o maintainers team

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

@mrunalp PTAL

### CODE REVIEW

**Comment by justaugustus** [comment]
Hey @umohnani8 -- in order to get added to this team, you'll need to also be a member of the `kubernetes-sigs`. Please file a [membership request issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) in this repo and follow the instructions detailed in that issue template.

/hold
/assign @mrunalp

**Comment by nikhita** [comment]
@justaugustus - @umohnani8 is already a member of kubernetes-sigs. ;)

https://github.com/kubernetes/org/blob/c8867fde7723a4e503b4728c061f2bb0cba2c849/config/kubernetes-sigs/org.yaml#L196

/hold cancel

**Comment by justaugustus** [comment]
Whoops! Must've missed that. :sweat_smile: 
/lgtm

**Pull request merged**
