### PR TITLE
Add nojnhuh to kubernetes org

### PR DESCRIPTION
**Pull request by nojnhuh**
Requesting membership to the kubernetes org as an existing member of kubernetes-sigs: https://github.com/kubernetes/org/issues/3771

fyi @CecileRobertMichon

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/close

in favor of https://github.com/kubernetes/org/pull/4116

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
