### PR TITLE
Add members 2019-06-27

### LINKED ISSUE #929: REQUEST: New membership for corneliusweig
### GitHub Username
@corneliusweig

### Organization you are requesting membership in
(at)kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects (krew)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ahmetb 
- @soltysh 

### List of contributions to the Kubernetes project
- PRs reviewed / authored: https://github.com/kubernetes-sigs/krew/pull/212, https://github.com/kubernetes-sigs/krew/pull/211, https://github.com/kubernetes-sigs/krew/pull/208, https://github.com/kubernetes-sigs/krew/pull/203, https://github.com/kubernetes-sigs/krew/pull/202, https://github.com/kubernetes-sigs/krew/pull/201, https://github.com/kubernetes-sigs/krew/pull/195, https://github.com/kubernetes-sigs/krew/pull/191, https://github.com/kubernetes-sigs/krew/pull/183, https://github.com/kubernetes-sigs/krew/pull/178, https://github.com/kubernetes-sigs/krew/pull/177, https://github.com/kubernetes-sigs/krew/pull/176
- Issues responded to: (among others) https://github.com/kubernetes-sigs/krew/issues/200, https://github.com/kubernetes-sigs/krew/issues/168, https://github.com/kubernetes-sigs/krew/issues/199, https://github.com/kubernetes-sigs/krew/issues/196, https://github.com/kubernetes-sigs/krew/issues/190, 
- SIG projects I am involved with: `krew`

### PR DESCRIPTION
**Pull request by nzoueidi**
Fixes #929 

/area github-membership

### CODE REVIEW

**Comment by corneliusweig** [comment]
Hi, thanks for taking care of this so quickly. Strangely, I still haven't received an invite to the organization yet. Is that expected?

@ahmetb pointed out that he was also added to the krew team section, like so:
```patch
diff --git a/config/kubernetes-sigs/sig-cli/teams.yaml b/config/kubernetes-sigs/sig-cli/teams.yaml
index dd670f5..75b86e6 100644
--- a/config/kubernetes-sigs/sig-cli/teams.yaml
+++ b/config/kubernetes-sigs/sig-cli/teams.yaml
@@ -38,10 +38,11 @@ teams:
   krew-maintainers:
     description: write access to krew
     members:
     - adohe
     - ahmetb
+    - corneliusweig
     - fabianofranz
     - janetkuo
     - liggitt
     - mengqiy
     - monopole
@@ -60,10 +61,11 @@ teams:
   krew-index-maintainers:
     description: write access to krew-index
     members:
     - adohe
     - ahmetb
+    - corneliusweig
     - fabianofranz
     - janetkuo
     - liggitt
     - mengqiy
     - monopole

```
Is that also necessary to receive an invite?

**Comment by nikhita** [comment]
@corneliusweig I think the tool that syncs users is broken atm, looking into it.

**Comment by cblecker** [comment]
@corneliusweig A piece of our CI was broken. You should now have an invite.

**Comment by corneliusweig** [comment]
@nikhita Not sure if you fixed it already, but I finally received the invite. Thanks for looking into this!

**Comment by corneliusweig** [comment]
@cblecker Yep, I've already received the invite. Thanks for looking into this!

**Pull request merged**
