### PR TITLE
Add 1.20 CI Signal Shadows to release-team and ci-signal team

### PR DESCRIPTION
**Pull request by RobertKielty**
This adds 1.20 CI Signal Shadows to Release Team

/sig release
/assign @justaugustus @alejandrox1 @tpepper @saschagrunert
cc @jeremyrickard @savitharaghunathan @hasheddan @palnabarun @lachie83

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by justaugustus — CHANGES_REQUESTED** [review]
/hold these folx need to also be added to the `ci-signal` team

**Pull request merged**
