### PR TITLE
Add members 2019-03-17

### LINKED ISSUE #611: REQUEST: New membership for feloy
### GitHub Username
@feloy

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @sieben
- @lledru

### List of contributions to the Kubernetes project
- PRs reviewed / authored
  - https://github.com/kubernetes/website/pull/13142
  - https://github.com/kubernetes/website/pull/13059
  - https://github.com/kubernetes/website/pull/13058
  - https://github.com/kubernetes/website/pull/12863
  - https://github.com/kubernetes/website/pull/12803
  - https://github.com/kubernetes/website/pull/13126
  - https://github.com/kubernetes/website/pull/12987
  - https://github.com/kubernetes-sigs/kustomize/pull/464
- Issues responded to
- SIG projects I am involved with
  - docs-fr translation team
  - kustomize
  - kubebuilder (https://conferences.oreilly.com/velocity/vl-eu-2018/public/schedule/detail/71703)

### LINKED ISSUE #613: REQUEST: New membership for @juan-lee
### GitHub Username
@juan-lee

### Organization you are requesting membership in
- kubernetes
- kubernetes-sigs

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @justaugustus 
- @tariq1890 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/51
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/136
- SIG projects I am involved with
https://github.com/kubernetes-sigs/cluster-api-provider-azure
https://github.com/kubernetes-sigs/cluster-api

### LINKED ISSUE #619: REQUEST: New membership for @MAKOSCAFEE
### GitHub Username
@MAKOSCAFEE

### Organization you are requesting membership in
- kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jimangel 
- @zparnold 

### List of contributions to the Kubernetes project
- PRs reviewed / authored- 
    - https://github.com/kubernetes/website/pull/12594
    - https://github.com/kubernetes/website/pull/12584
    - https://github.com/kubernetes/website/pull/12397
    - https://github.com/kubernetes/community/pull/2713
    - https://github.com/kubernetes/community/pull/2710
- Issues responded to    
    - https://github.com/kubernetes/enhancements/issues/596
    - https://github.com/kubernetes/website/issues/12389
    - https://github.com/kubernetes/enhancements/issues/603
    - https://github.com/kubernetes/enhancements/issues/625
    - https://github.com/kubernetes/community/issues/2599
    - https://github.com/kubernetes/community/issues/2599
- SIG projects I am involved with
    - Docs shadow for 1.13 release
    - Docs shadow for 1.14 release

### PR DESCRIPTION
**Pull request by mrbobbytables**
fixes #611 
fixes #613 
fixes #619 

/area github-membership

### CODE REVIEW

**Comment by nikhita** [comment]
In the mood for a joke this morning...

/joke

**Comment by juan-lee** [comment]
@mrbobbytables @justaugustus @nikhita Oddly I don't seem to appear in the kubernetes or kubernetes-sigs orgs. Perhaps it has something to do with the hyphen in my username. Any ideas?

**Comment by mrbobbytables** [comment]
@juan-lee Can you try going here:
https://github.com/orgs/kubernetes/invitation
https://github.com/orgs/kubernetes-sigs/invitation

The links should have been sent to you in your email from github, but to be added as a member you must first accept the org invitation.

**Comment by juan-lee** [comment]
ha! rtfm

thanks @mrbobbytables

**Pull request merged**
