### PR TITLE
Add dims as admin to aws-* related repos

### PR DESCRIPTION
**Pull request by dims**
Volunteering to help with admin duties as some folks are heading (or already) on vacation. Some folks have moved on as well, but will leave cleanup for later.

### CODE REVIEW

**Comment by sftim** [comment]
(thanks for stepping up)

**Comment by nikhita** [comment]
> pull-org-test-all — Pod pending timeout. 

Likely due to https://github.com/kubernetes/k8s.io/issues/5473. Slack discussion is going on in [this thread](https://kubernetes.slack.com/archives/CCK68P2Q2/p1687935316175379)

**Comment by dims** [comment]
just in time ... https://github.com/kubernetes-sigs/aws-iam-authenticator releases are not being generated from the github actions :(

**Comment by dims** [comment]
@nikhita @MadhavJivrajani this is ready!

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
