### PR TITLE
Update sig-docs-hi reviewers

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
Adding @verma-kunal as reviewer for `hi` localization.

cc: 
@verma-kunal 
@sftim 
@divya-mohan0209 
@mittalyashu

### CODE REVIEW

**Comment by cblecker** [comment]
@sftim This one likely needs an `/approve` from you too

**Comment by mittalyashu** [comment]
/approve

Thanks for the awesome work @verma-kunal

**Pull request merged**
