### PR TITLE
Add 1.30 Comms shadows to github teams

### PR DESCRIPTION
**Pull request by kcmartin**
What type of PR is this:
/kind documentation

What this PR does / why we need it:
Add 1.30 Comms Shadows to sig-release team

/assign @katcosgrove @gracenng @neoaggelos @ramrodo @sanchita-07 @fsmunoz

### CODE REVIEW

**Comment by ramrodo** [comment]
Hi @kcmartin, you or @fkautz need to create an issue to add him as a member of Kubernetes Org to have the tests in green.

**Review by katcosgrove — COMMENTED** [review]
This section had to be in alphabetical order, but then you'll be good to merge!

**Comment by kcmartin** [comment]
Is there anything else I need to do -- I see "Merging is blocked" / protected branch. @katcosgrove ?

**Comment by ramrodo** [comment]
> Is there anything else I need to do -- I see "Merging is blocked" / protected branch. @katcosgrove ?

@kcmartin This PR will be automatically merged once it has "approved" and "lgtm" labels from authorized users.

**Review by sanchita-07 — APPROVED** [review]

**Review by justaugustus — APPROVED** [review]

**Pull request merged**
