### PR TITLE
Add members 2020-09-23 Part 2

### LINKED ISSUE #2211: REQUEST: New membership for @ScrapCodes
### GitHub Username
@ScrapCodes

### Organization you are requesting membership in
@kubernetes

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [ x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [ x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [ x] I am actively contributing to 1 or more Kubernetes subprojects
- [ x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @RobertKielty 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- PRs reviewed / authored
https://github.com/kubernetes/kubernetes/pull/94717
https://github.com/kubernetes/kubernetes/pull/94716
https://github.com/kubernetes/kubernetes/pull/90165
https://github.com/kubernetes/kubernetes/pull/89725
https://github.com/kubernetes/kubernetes/pull/88364
https://github.com/kubernetes/kubernetes/pull/94082

- Issues responded to
https://github.com/kubernetes/kubernetes/issues/94520
https://github.com/kubernetes/kubernetes/issues/89719
https://github.com/kubernetes/kubernetes/issues/94221

- SIG projects I am involved with
release - Shadow at CI signal team

### LINKED ISSUE #2212: REQUEST: New membership for thejoycekung
### GitHub Username
@thejoycekung

### Organization you are requesting membership in
@kubernetes 

### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @RobertKielty 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- SIG projects I am involved with:
Release - CI Signal Shadow for 1.20

### LINKED ISSUE #2215: REQUEST: New membership for MonzElmasry
### GitHub Username
@MonzElmasry
### Organization you are requesting membership in
@kubernetes
### Requirements
- [x] I have reviewed the community membership guidelines (https://git.k8s.io/community/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubernetes-dev e-mail list (https://groups.google.com/forum/#!forum/kubernetes-dev)
- [x] I am actively contributing to 1 or more Kubernetes subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @bai 
- @jeremyrickard 

### List of contributions to the Kubernetes project
- SIG projects I am involved with:
Release - Bug Triage Shadow for 1.20

### PR DESCRIPTION
**Pull request by palnabarun**
fixes #2211
fixes #2212
fixes #2215

### CODE REVIEW

**Comment by palnabarun** [comment]
/hold

(for a few hours for more membership requests)

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm so far

**Comment by palnabarun** [comment]
/assign @nikhita @mrbobbytables

(since prow didn't catch the command the first time)

**Review by idvoretskyi — APPROVED** [review]
/approve

**Comment by savitharaghunathan** [comment]
/lgtm

(My first lgtm did not add any label)

**Comment by palnabarun** [comment]
/hold cancel

(cancelling the hold so as to not block the new contributors :slightly_smiling_face:)

**Review by savitharaghunathan — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
@savitharaghunathan @ameukam -- Need a re-lgtm. :slightly_smiling_face: Sorry to bother again.

Thank you in advance. :chocolate_bar:

**Comment by palnabarun** [comment]
@savitharaghunathan Thanks! That was lightning quick. :zap:

**Pull request merged**
