### PR TITLE
update ci-signal team members for 1.18 release cycle

### PR DESCRIPTION
**Pull request by droslean**

### CODE REVIEW

**Comment by droslean** [comment]
/hold

Waiting for @hrishin and  @jpreese to become members.

**Comment by justaugustus** [comment]
Non-org members have been removed from the PR, so:
/lgtm
/approve
/hold cancel

**Comment by droslean** [comment]
/hold cancel

Let's not include them for now. I would like to merge it like this, to prevent spamming the members of the previous release.
I will add them later on.

**Comment by droslean** [comment]
@justaugustus you are quick :D

**Pull request merged**
