### PR TITLE
Add danielqsj as a member to sig instrumentation teams

### PR DESCRIPTION
**Pull request by danielqsj**
I'd like to help/participate in reviews and discussions related to sig instrumentation.

/cc @brancz @piosz @fabxc

### CODE REVIEW

**Comment by brancz** [comment]
I couldn't find an any documentation on a process for this (as in if this is all we need to do), but we're happy to have you!

/lgtm

**Comment by brancz** [comment]
Maybe @spiffxp can tell us :slightly_smiling_face: .

**Comment by nikhita** [comment]
> I couldn't find an any documentation on a process for this (as in if this is all we need to do)

We still need to document process guidelines for this (https://github.com/kubernetes/org/issues/336#issuecomment-453706817), but this should be good enough for now. :)

**Comment by brancz** [comment]
Thanks for clarifying @nikhita! :slightly_smiling_face: Yes sounds like this is all that is needed.

**Pull request merged**
