### PR TITLE
Adding 1.27 enhancements team to appropriate groups

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Adding 1.27 enhancements shadows to appropriate groups

/assign @salaxander @JamesLaverack

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold

We are VERY Particular about git history in this repo. Org memberships are one person per commit and must follow this format:

```
Add <foo> to <org>
```

or for multiple orgs

```
Add <foo> to <org>, <org>, <org>
```

team memberships must be separate.

**Comment by marosset** [comment]
updated - @mrbobbytables PTAL

**Comment by marosset** [comment]
Let me split this up into 2 different PRs. One to add members to the org and another to update the groups.
It looks like the CI job may be validating against main for or membership

**Comment by palnabarun** [comment]
Let's do this as a 2 step process. A new org coordinator can raise the PR for adding new members (I can do that for all the RT new members) and you can PR them into the required teams.

**Comment by marosset** [comment]
> Let's do this as a 2 step process. A new org coordinator can raise the PR for adding new members (I can do that for all the RT new members) and you can PR them into the required teams.

Beat you to it :) Let me know if you want me to close the other PR I just opened to add the new org members.

**Comment by palnabarun** [comment]
Hehe! That PR is fine. 

One problem though, the sponsorship requirements are not yet met. Both people who +1ed in the two requests are from the same company. (Just a paperwork issue for now. Can be mitigated by someone else from the Release Team +1ing those requests)

**Comment by marosset** [comment]
> Hehe! That PR is fine.
> 
> One problem though, the sponsorship requirements are not yet met. Both people who +1ed in the two requests are from the same company. (Just a paperwork issue for now. Can be mitigated by someone else from the Release Team +1ing those requests)

@JamesLaverack can you take a look when you get a chance?
Thanks!

**Comment by dims** [comment]
@marosset error in CI `config_test.go:272: The team milestone-maintainers in org Kubernetes has an unsorted list of members`

**Comment by marosset** [comment]
@dims - the CI checks are all passing now :)

**Comment by dims** [comment]
/approve
/lgtm

please remove hold when you all feel ready

**Comment by marosset** [comment]
/hold cancel
The org membership changes have merged

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
