### PR TITLE
Add sladyn98 to wg structured logging

### PR DESCRIPTION
**Pull request by sladyn98**
I would like to be an reviewer for structured logging
/cc @serathius @shubheksha

### CODE REVIEW

**Comment by serathius** [comment]
/lgtm
/approve
Welcome

**Comment by serathius** [comment]
FYI I think those lists need to be kept ordered alphabetical.

**Comment by mrbobbytables** [comment]
This PR has been open for awhile now...is it still needed? If not, I'd go ahead and close it out.

**Comment by palnabarun** [comment]
Closing for now. Please feel free to reopen whenever needed. :)

/close

**Pull request closed without merging**
