### PR TITLE
add coffeepac to several of the sig-inst lists

### PR DESCRIPTION
**Pull request by coffeepac**
I have been a part of the sig for a while and am looking for more day-to-day interaction

### CODE REVIEW

**Comment by piosz** [comment]
/lgtm
/approve
Pat has been a maintainer for ELK stack in Kubernetes since ages. In addition to this doing plenty of things for SIG Instrumentation, including hosting f2f meeting.

**Comment by piosz** [comment]
cc @brancz @logicalhan @ehashman

**Comment by logicalhan** [comment]
Welcome Pat!!

**Comment by piosz** [comment]
Oh, you missed the first section: `sig-instrumentation-api-reviews`

**Comment by coffeepac** [comment]
@piosz I don't know that I have sufficient knowledge of k8s APIs to handle those reviews.  However, maybe its not so big and I should just ask for help if I feel I'm in too deep?

**Pull request merged**
