### PR TITLE
github/team: rename product-security-committee team to product-security-response

### PR DESCRIPTION
**Pull request by cpanato**
ref: https://github.com/kubernetes/community/issues/5596

/assign @nikhita @spiffxp

### CODE REVIEW

**Review by idvoretskyi — APPROVED** [review]
/lgtm

/hold

**Review by idvoretskyi — COMMENTED** [review]
Actually, this should not include the "Product" word in title of the group anymore - https://github.com/kubernetes/org/pull/2915

**Comment by cpanato** [comment]
> Actually, this should not include the "Product" word in title of the group anymore - #2915

will remove the product!

**Pull request merged**
