### PR TITLE
security-profiles-operator: Add JAORMX and jhrozek as admins

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 96f254e226d975be65234e6e54939c3e5b5be55d

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 83ecaa4ebefd06a220dcfb4f28ff58cd579ef7d6

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 8100d37aa9f27194fb3bdf709281097159672ded

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
